feat(conf): make unified report configurable
fossology/fossology pull request #1759
Opened 2020-07-08 05:23 UTC by shaheemazmalmmd

## Description

Checkbox to include/exclude tables in Unified Report.

### Changes

* Add table with headings in text field and checkbox.
* Include/exclude by enable/disable checkbox.
* Edit headings from text field.

## How to test

* Upload a package.
* Go to conf page and un-check headings and submit.
* Download unified report. unchecked tables under headings shouldn't exists.
* Change heading name and see if the changes appear in report.

2020-07-16 12:11 UTC, shaheemazmalmmd commented
Will re-base the branch once https://github.com/fossology/fossology/pull/1747 gets merged.

2020-12-07 06:05 UTC, GMishx commented
Can you please increase the width of the table? It is very difficult to see everything available in the text boxes.

![image](https://user-images.githubusercontent.com/18077542/101315122-f5c0fe00-387f-11eb-8dc7-39493201eb06.png)

2020-12-07 06:09 UTC, GMishx commented
Also, the following two header texts did not change with the text from DB:
1. Export Restrictions
2. Clearing Protocol Change Log

2020-12-07 06:28 UTC, GMishx commented on src/www/ui/core-schema.dat
> +  $Schema["TABLE"]["report_info"]["ri_unifiedcolumns"]["DESC"] = "";
It will be nice to have a column description.

2020-12-15 09:31 UTC, GMishx requested changes
One tiny change.

2020-12-15 09:31 UTC, GMishx commented on src/unifiedreport/agent/unifiedreport.php
> +    print_r($unifiedColumns['exportrestrictions']);
Please remove debugging statement.

2020-12-15 11:25 UTC, GMishx approved these changes
Changes looks good. Tested, working fine.

2020-12-16 08:13 UTC, merged