feat(about): add new page for third party licenses
fossology/fossology pull request #1829
Opened 2020-11-05 09:12 UTC by shaheemazmalmmd

## Description

* Add html file with all the licenses involved in fossology.

## How to test

* Install FOSSology and check third party license license page.

2020-11-19 08:27 UTC, mcjaeger commented
ehem? 
<img width="781" alt="Screenshot 2020-11-19 at 09 26 33" src="https://user-images.githubusercontent.com/3418977/99640580-60cda080-2a49-11eb-8c06-8f53d9f1d731.png">

2020-11-24 23:34 UTC, mcjaeger commented
updated the info also in about menu item. tested with vagrant. looks OK on my side.

2020-11-25 08:33 UTC, GMishx requested changes
Also, the docker tests are failing. I investigated a little bit and found there is a `NOTICES*` entry in `.dockerignore`. Can you please change that entry to `NOTICES` and `NOTICES.spdx`?

2020-11-25 08:33 UTC, GMishx commented on src/www/ui/page/AboutPage.php
> +  );
Can you please fix the indentation by adding 2 more spaces?

2020-11-25 11:58 UTC, GMishx approved these changes

2020-11-26 05:01 UTC, merged