refactor(login): updated password hashing algorithm
fossology/fossology pull request #1851
Opened 2020-12-20 16:05 UTC by Aman-Codes

## Description

Currently fossology uses SHA-1 which is now officially deprecated. 
Also as per the [official website](https://www.php.net/manual/en/function.password-hash.php), the salt option of PASSWORD_BCRYPT has been deprecated as of PHP 7.0.0

### Changes

Updated password hashing algorithm from SHA1 to PASSWORD_DEFAULT (Use the bcrypt algorithm)

Closes #841

2020-12-20 16:08 UTC, Aman-Codes commented
Can you guide me which function to call in below 2 cases to save new hash in database
[here](https://github.com/Aman-Codes/fossology/blob/login/src/www/ui/core-auth.php#L316) and [here](https://github.com/Aman-Codes/fossology/blob/login/src/lib/php/common-auth.php#L167)

2021-01-05 08:06 UTC, GMishx commented
> Can you guide me which function to call in below 2 cases to save new hash in database
> [here](https://github.com/Aman-Codes/fossology/blob/login/src/www/ui/core-auth.php#L316) and [here](https://github.com/Aman-Codes/fossology/blob/login/src/lib/php/common-auth.php#L167)

Hey, unfortunately there is not function right now to update passwords. You can create a new function in `src/lib/php/common-users.php` and use that (note, the function will be included automatically in all PHP files).

2021-01-05 08:14 UTC, GMishx requested changes

2021-01-05 08:14 UTC, GMishx commented on install/db/dbmigrate_2.1-2.2.php
> +} // Migrate_21_22
Please revert unnecessary change.

2021-01-06 04:25 UTC, Aman-Codes commented on install/db/dbmigrate_2.1-2.2.php
> +} // Migrate_21_22
Did the change

2021-01-06 10:29 UTC, GMishx approved these changes
Changes looks good. Needs test.

2021-01-06 10:47 UTC, GMishx commented
FOSSology allows users without passwords and to accomplish that, it checks for empty `seed`.
https://github.com/fossology/fossology/blob/479322e49e87f94f41d846452d6167ec85f63ea9/src/www/ui/core-auth.php#L310

So @Aman-Codes, please put some default values like `Seed` for the `user_seed` whenever the password is either updated or a new user is created. With the current implementation, if I edit an account and change it's password, I can login with that account without a password as seed is empty for it.

2021-01-06 11:47 UTC, Aman-Codes commented
@GMishx  Updated the default seed value

2021-01-07 05:58 UTC, GMishx approved these changes
Tested, working as expected.

2021-01-07 06:01 UTC, merged