feat(reuse): Change data type of reuse_group from int to string.
fossology/fossology pull request #1864
Opened 2021-01-06 19:39 UTC by YashJipkate

## Description

This PR changes the data type of reuse_group from int to string. Fixes #1801.

### Changes

The data type of reuse_group and reuseGroup is changed to string. The files affected are [Reuser.php](https://github.com/fossology/fossology/blob/master/src/www/ui/api/Models/Reuser.php), [openapi.yaml](https://github.com/fossology/fossology/blob/master/src/www/ui/api/documentation/openapi.yaml) and [JobController.php](https://github.com/fossology/fossology/blob/master/src/www/ui/api/Controllers/JobController.php).

## How to test

- Upload some files to scan and reuse a resource.
- There should be no console errors.

2021-01-06 19:40 UTC, YashJipkate commented
@GMishx Can you suggest some better testing method. I couldn't find anything in the wiki.

2021-01-07 06:26 UTC, GMishx requested changes
The following line needs to be updated as well. You can use `UserDao::getGroupIdByName()` to get the group id.
https://github.com/fossology/fossology/blob/479322e49e87f94f41d846452d6167ec85f63ea9/src/www/ui/api/Models/ScanOptions.php#L152

2021-01-07 06:26 UTC, GMishx commented on src/www/ui/api/Models/Reuser.php
> +        "reuse_upload should be integers", 400);
```suggestion
        "reuse_upload should be integer", 400);
```

2021-01-07 06:28 UTC, GMishx commented
Also, since it is a breaking change, can you please update the API version in `openapi.yaml` to `1.2.0` ?

2021-01-07 08:31 UTC, YashJipkate commented on src/www/ui/api/Models/Reuser.php
> +        "reuse_upload should be integers", 400);
Done!

2021-01-07 08:33 UTC, YashJipkate commented
> The following line needs to be updated as well. You can use `UserDao::getGroupIdByName()` to get the group id.
> 
> https://github.com/fossology/fossology/blob/479322e49e87f94f41d846452d6167ec85f63ea9/src/www/ui/api/Models/ScanOptions.php#L152

Done [here](https://github.com/fossology/fossology/pull/1864/files#diff-403b549d9fe4ea61ed66944e5002b7a1afa104d6bfd4888cd58b4e65ac6098ddR153)


> Also, since it is a breaking change, can you please update the API version in `openapi.yaml` to `1.2.0` ?

Done.

2021-01-07 08:52 UTC, GMishx approved these changes
Changes looks good. Needs test/

2021-01-07 17:16 UTC, YashJipkate commented
> Changes looks good. Needs test/

Could you please elaborate? Do I need to write tests?

2021-01-08 08:55 UTC, GMishx commented
> Could you please elaborate? Do I need to write tests?

Oh, so we do pair reviews before merging. One does a code review and one does testing (installing the branch and checking the functionality).
I have reviewed the source code and now someone needs to test it before merging.

2021-01-15 09:32 UTC, GMishx commented on src/www/ui/api/Models/Reuser.php
> +      throw new \UnexpectedValueException("Reuse group should be a srting!", 400);
A small typo with `string`.

2021-01-15 09:32 UTC, GMishx approved these changes
Tested, working as expected.

2021-01-15 09:34 UTC, GMishx commented
Hello @YashJipkate , can you please rebase your branch with master once #1863 is merged? (it will create another merge conflict). I will comment here once the branch is merged.

2021-01-15 10:15 UTC, GMishx commented
Hi, #1863 is merged just now. You can rebase the branch with `master` to resolve conflicts.

2021-01-15 11:53 UTC, GMishx commented
Hi @YashJipkate , we prefer a rebase over branch merge to keep the git history clean and sane. You can refer to point 4 & 5 in **Pull Requests** in our [contributing guidelines](https://github.com/fossology/fossology/blob/master/CONTRIBUTING.md#pull-requests) to know the git commands.

2021-01-15 14:42 UTC, YashJipkate commented
@GMishx I have now rebased properly. Please take a look.

2021-01-15 18:25 UTC, merged