Fixes parts of #1913: Migrate docker tests
fossology/fossology pull request #1915
Opened 2021-03-12 09:38 UTC by NishealJ

## Description

This PR fixes parts of  #1913 & migrates the docker test from Travis to Github Actions

### Changes

- Added worker for docker test

## How to test
-

2021-03-15 08:10 UTC, GMishx requested changes

2021-03-15 08:10 UTC, GMishx commented on src/testing/docker/test-standalone.sh
> +docker-compose exec -T web /usr/local/share/fossology/copyright/agent/copyright -h
The script is made to test the Docker environment built from single container and not from `docker-compose`. For that, the file `src/testing/docker/test-cluster.sh` is used. Can you please revert the changes to `docker exec`?

2021-03-15 08:10 UTC, GMishx commented on src/testing/docker/test-standalone.sh
> +docker-compose up -d
For the same reason, can you please remove `docker-compose up` and build only the `web` container as before?
The line bellow already starts a container for the tests.

2021-03-15 08:11 UTC, GMishx commented
Also, can you please change and squash your commits to follow the [contributing guidelines](https://github.com/fossology/fossology/blob/master/CONTRIBUTING.md#git-commit-conventions)?

2021-03-23 07:04 UTC, NishealJ commented
Will re-open this PR with fixes.

2021-03-23 07:04 UTC, closed without merging