chore(dependency): update jquery and select2 version
fossology/fossology pull request #1947
Opened 2021-04-05 09:26 UTC by Aman-Codes

## Description

Updated dependencies having security vulnerabilities. 

Closes #1946  

### Changes

- Updated jQuery version from 3.3.1 to 3.6.0
- Updated select2 version from 4.0.5 to 4.0.13

2021-04-05 10:14 UTC, GMishx commented
Hi @Aman-Codes , can you please add `install/db/db.cron` and `install/fossdash/fossdash-publish.py` to `.gitignore` so they do not end up in commits by mistake?

2021-04-05 10:31 UTC, Aman-Codes commented
> Hi @Aman-Codes , can you please add `install/db/db.cron` and `install/fossdash/fossdash-publish.py` to `.gitignore` so they do not end up in commits by mistake?

Updated the .gitignore file

2021-04-05 10:32 UTC, GMishx approved these changes
Changes looks good. Needs test.

2021-04-08 12:18 UTC, GMishx commented
https://github.com/fossology/fossology/blob/03c27e1183af2cfd99b9ff927648ad1aa9b47c64/src/www/ui/template/ui-browse.js.twig#L65
Please replace `fnDraw()` with `draw()`.

2021-04-08 12:31 UTC, GMishx requested changes

2021-04-08 12:31 UTC, GMishx commented on src/www/ui/template/ui-browse.js.twig
> +    browseTable.Draw();
I am sorry, it is supposed to be `draw()`
https://datatables.net/reference/api/draw()

2021-04-08 12:35 UTC, GMishx approved these changes
Tested, working fine.

2021-05-07 11:24 UTC, merged