feat(upload): make global decisions configurable in all upload pages
fossology/fossology pull request #2122
Opened 2021-12-03 08:17 UTC by shaheemazmalmmd

## Description

Make global decision configurable. from all upload pages.

### Changes

* add a function to store values in report_info page;

## How to test

* Upload a package and do some clearing with global decisions.
* Upload a some other version of package again and see if there are decisions applied automatically.
* Upload a some other version of package by clicking "Apply global decisions for selected upload" and check the global decisions in your package.

2021-12-06 07:12 UTC, GMishx requested changes
Some suggestions about changes.

2021-12-06 07:12 UTC, GMishx commented on src/lib/php/Dao/ClearingDao.php
> +      $applyGlobal = "";
Unused variable. Should it be placed in the return sql string?

2021-12-06 07:12 UTC, GMishx commented on src/lib/php/UI/template/include/upload.html.twig
> +          <img src="images/info_16.png" data-toggle="tooltip" title="{{'Apply results of concluded files with global from previous uploads'|trans}}" alt="" class="info-bullet"/>
```suggestion
          <img src="images/info_16.png" data-toggle="tooltip" title="{{'Apply results of concluded files marked as global from previous uploads'|trans}}" alt="" class="info-bullet"/>
```

2021-12-06 07:12 UTC, GMishx commented on src/lib/php/UI/template/include/upload.html.twig
> +          {{ 'Apply global decisions for selected upload'| trans }}
```suggestion
          {{ 'Apply global decisions for current upload'| trans }}
```

2021-12-06 07:12 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +        - name: applyglobal
```suggestion
        - name: applyGlobal
```

2021-12-06 07:12 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +            Apply global decisions for selected upload
```suggestion
            Apply global decisions for current upload
```

2021-12-06 07:12 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +        - name: applyglobal
Please change the patch version of REST API to mark new changes.

2021-12-06 07:12 UTC, GMishx commented on src/www/ui/core-auth.php
> +    $_SESSION['BannerOption'] = 1;
Potential changes from other branch?

2021-12-06 07:12 UTC, GMishx commented on src/www/ui/core-schema.dat
Please add missing `ALTER` statement for the new column.

2022-01-13 08:18 UTC, GMishx commented
There seems to be some inconsistency with the results.
I had an upload with GPL-3.0 license where global decision of GPL-3.0 was added. After re-uploading the same package without selecting "Apply global decisions for current upload", the file appears cleared in tree view.

![image](https://user-images.githubusercontent.com/18077542/149291515-a7ba09c0-b0c3-4d88-b7d4-3d65df428025.png)

And single file view shows file as cleared.

![image](https://user-images.githubusercontent.com/18077542/149291947-a9d7903d-5554-4044-8ce6-f7f5dec0579c.png)

But Unified Clearing report has no license decision.

2022-01-19 09:59 UTC, ag4ums approved these changes
Code looks good and work as expected

2022-01-19 10:01 UTC, merged