feat(API): Created an API end-point for copyright
fossology/fossology pull request #2165
Opened 2022-02-22 12:14 UTC by aman1971

## Description

Added a new API endpoint for   `/uploads/{id}/copyright`.

see #2081 for details.

### Changes

`/uploads/{id}/copyright` endpoint added.
. Returns the list of licenses and copyright. 

## How to test

Send a get request to `/uploads/{id}/copyright` and check the response .

Closes #2081

2022-03-09 09:11 UTC, GMishx commented
Thank you for your contributions @aman1971 but I believe this change does not require additional `/uploads/{id}/copyright` endpoint as it returns both license and copyrights.

Instead, how about modifying the existing `/uploads/{id}/licenses` endpoint and add a parameter in request like
```yaml
- name: copyright
  required: false
  description: Show copyrights in response
  in: query
  schema:
    type: boolean
    default: false
```

And if possible, add another one for `license`.

So whoever needs only license, can query the endpoint with `copyright=false` and who needs with copyright can query with `copyright=true`.

In my opinion, `/uploads/{id}/copyright` should return only copyrights if implemented and not licenses as well.

2022-03-10 13:34 UTC, aman1971 commented
Thanks for the feedback @GMishx . I am working on changes just to be sure I am making changes in `/uploads/{id}/licenses` and adding a parameter in request for `license`  and `copyright`.

2022-04-19 17:50 UTC, soham4abc approved these changes

2022-04-19 17:51 UTC, soham4abc commented
@GMishx  PTAL

2022-05-05 05:05 UTC, GMishx requested changes
Small changes required.

2022-05-05 05:05 UTC, GMishx commented on src/www/ui/api/Helper/UploadHelper.php
> +            $copyrightContent = 'null';
```suggestion
            $copyrightContent = null;
```

2022-05-05 05:05 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +        description: Show lisense in response
```suggestion
        description: Show license in response
```

2022-05-05 05:17 UTC, GMishx commented
Tested, working as expected with the suggested changes.

2022-05-30 12:07 UTC, GMishx approved these changes
Changes looks good. Needs another round of testing.

2022-06-01 09:40 UTC, GMishx approved these changes
Tested, working as expected.

2022-06-01 09:41 UTC, GMishx commented
Hello @aman1971 , some tests are failing. Please fix them.

And squash your commits to one for us to merge the PR.

2022-06-06 09:47 UTC, merged