fix(api): Return full uploadId
fossology/fossology pull request #2174
Opened 2022-03-08 09:17 UTC by TassiloPitrasch

Removed unnecessary subindex to return full uploadId instead of first digit only

## Description

When uploading a package from URL via the API, the uploadId in the response is not complete, but only the first digit. This is caused by an unnecessary "subindex", which was removed. Maybe this issue was created with a change in the database structure.

### Changes

Removed subindex for array $uploadResponse.

## How to test

This can easily be tested by checking the response for an API call as described in https://www.fossology.org/get-started/basic-rest-api-calls/ under "Upload a package".

2022-03-08 09:45 UTC, patrickwjh approved these changes
I can approve the fix. By the second access "[0]" to the uploadResponse only the first character of the string is accessed, which causes the error that the complete UploadId is not returned. 

The fix was tested and the complete UploadId is returned again!

2022-03-08 10:46 UTC, GMishx requested changes

2022-03-08 10:46 UTC, GMishx commented on src/www/ui/api/Controllers/UploadController.php
> +        $uploadId = $uploadResponse[3];
This change will cause issues for file uploads as the third argument returned is an array and clients expect integer
https://github.com/fossology/fossology/blob/1f490d46d79ae9ea85ff0de279083b271147bbc5/src/www/ui/page/UploadFilePage.php#L201-L202

To fix that, following location must be updated
https://github.com/fossology/fossology/blob/1f490d46d79ae9ea85ff0de279083b271147bbc5/src/www/ui/api/Helper/UploadHelper/HelperToUploadFilePage.php#L47

to something like this
```php
$response = $this->handleUpload($request);
$response[3] = $response[3][0];
return $response;
```

2022-03-09 11:22 UTC, TassiloPitrasch commented
@GMishx Thanks for the feedback! I updated the respective method.

2022-03-09 12:26 UTC, GMishx approved these changes
Changes looks good.

2022-03-09 12:27 UTC, GMishx commented
@TassiloPitrasch that's for fast response. Can you please rebase your branch and squash the commits so we do not get 2 merge commits?

2022-03-09 12:31 UTC, GMishx approved these changes
Tested, working as expected.﻿

2022-03-09 15:49 UTC, GMishx commented
> @GMishx I checked the failing test. As far as i understood, the test asserts an array with one single entry "20" for the uploadId. We changed that now to a single String. Maybe we need to adapt the test here...

I guess so too. The upload id `[20]` should now be single value due to change in upload helper
https://github.com/fossology/fossology/blob/fcf1de2f4beb714bd67131cbeeba2604f3ee1fb4/src/www/ui_tests/api/Controllers/UploadControllerTest.php#L583

2022-03-10 08:02 UTC, TassiloPitrasch commented
@GMishx But additionally, the returned ID was "1", not "20", where might this discrepancy come from?

2022-03-14 10:52 UTC, GMishx commented
I think PHP is translating `intval([20])` as `1`. There is a check for response code `201` and it returned only here
https://github.com/fossology/fossology/blob/7b3dab6b4ae7109242ff4d81fd4179ea66423f45/src/www/ui/api/Controllers/UploadController.php#L390-L397

2022-03-15 15:35 UTC, TassiloPitrasch commented
So, we will change intval als well and just use 20 as String for assertion?

2022-03-15 16:16 UTC, GMishx commented
No no, just change the return value of mock function to be simple integer and not array. The API should return integer and not string, therefore it is explicitly converted using `intval()`.

2022-03-16 15:45 UTC, TassiloPitrasch commented
@GMishx I guess, we're finished here!

2022-03-17 05:01 UTC, GMishx commented
Hey @TassiloPitrasch , is it possible to rebase the changes with latest `master` branch?
If I look at commits, I see a merge commit and this big commit https://github.com/fossology/fossology/pull/2174/commits/514e8cf13143101f1acb77eddb4e9b2eafce0063 which is not exactly limited to your changes.

If you can fix that, I can merge this PR.

2022-03-17 10:31 UTC, TassiloPitrasch commented
@GMishx I squashed the commit and reopened the Pull Request. If your fine with that, please merge :)

2022-03-17 10:51 UTC, GMishx commented
Perfect. Thank you @TassiloPitrasch

2022-03-17 11:56 UTC, merged