Fossology/highlight row
fossology/fossology pull request #2192
Opened 2022-03-27 05:55 UTC by Pendyala-thanvi

Signed-off-by: Thanvi Pendyala [[thanvipendyala194@gmail.com](mailto:thanvipendyala194@gmail.com)]

## Description
Fixes issue  #797
This change highlights a part of row when the user deletes it from the copyright/ URL/ Email/Author analysis tables.

### Changes
```src/copyright/ui/template/copyrighthist_scripts.html.twig```
```src/copyright/ui/template/histTable.js.twig```
```src/copyright/ui/template/ui-xp-view_rhs.html.twig```

Added changes to highlight the row of table when user deletes it.

## How to test
1. Upload any package and do some clearing.
2. Open the copyright/ URL/ Email/Author browser.
3. Delete any row by clicking on the delete icon.

2022-03-28 10:53 UTC, GMishx approved these changes
Changes looks good. Needs test.

2022-03-28 10:54 UTC, GMishx commented
@Pendyala-thanvi please squash your commits to a single commit.

2022-04-06 05:20 UTC, GMishx commented
@Pendyala-thanvi , I think the issue #797 talks about highlighting the complete deleted row.
The current changes only highlight the "deactivated" information text.

![image](https://user-images.githubusercontent.com/18077542/161901219-5ac5449c-f011-495d-b103-83d102e02ffe.png)

2022-05-05 06:08 UTC, GMishx requested changes
Please check the last comment about requirement of the issue.

2022-05-16 04:57 UTC, GMishx commented
@Pendyala-thanvi do you have any updates for the PR?

2022-06-13 04:29 UTC, GMishx commented
@Pendyala-thanvi, can you please provide any updates about the PR?

2022-09-26 06:19 UTC, shaheemazmalmmd commented
@Pendyala-thanvi Please re-open the PR in case you decide to make the suggested changes.

2022-09-26 06:19 UTC, closed without merging