feat(reuse): REUSE best practices for licensing/copyright part-3
fossology/fossology pull request #2263
Opened 2022-07-16 03:16 UTC by rohitpandey49

Signed-off-by: Rohit Pandey <rohit.pandey4900@gmail.com>

## Description

REUSE best practices for licensing/copyright

### Changes

1. Implemented correct licensing/copyright format

### Current REUSE status

When running reuse lint over this branch, the result is as follows:

```
* Files with copyright information: 4364 / 4364
* Files with license information: 4364 / 4364
```

Before that we were at:

```
* Files with copyright information: 4152 / 4360
* Files with license information: 3723 / 4360
```

2022-07-17 13:53 UTC, GMishx commented
Please change the license of `NOTICES.spdx` from `GPL-2.0-only` to `CC0-1.0` as written in the file.

2022-07-17 14:19 UTC, GMishx requested changes

2022-07-17 14:19 UTC, GMishx commented on src/www/ui/core-schema.dat
> +# SPDX-License-Identifier: GPL-2.0-only
It is a PHP file
```suggestion
/*
 SPDX-FileCopyrightText: © Fossology contributors

 SPDX-License-Identifier: GPL-2.0-only
*/
```

2022-07-17 14:19 UTC, GMishx commented on src/www/ui/scripts/jquery.treeview.js
> + * SPDX-License-Identifier: MIT AND GPL-3.0-only
```suggestion
 * SPDX-License-Identifier: MIT AND GPL-2.0-only
```

2022-07-17 14:19 UTC, GMishx commented on src/www/ui/scripts/jquery.validate.js
> + * SPDX-License-Identifier: MIT AND GPL-3.0-only
```suggestion
 * SPDX-License-Identifier: MIT AND GPL-2.0-only
```

2022-07-17 14:19 UTC, GMishx commented on src/www/ui/template/admin-folder-edit-form.html.twig
> +{# SPDX-FileCopyrightText: © ossology contributors
```suggestion
{# SPDX-FileCopyrightText: © FOSSology contributors
```

2022-07-17 16:43 UTC, rohitpandey49 commented
Corrected @GMishx sir

2022-07-20 14:02 UTC, GMishx requested changes
For `NOTICES.spdx`, there are several unnecessary changes. Can you please revert the file content and maybe use some basic editors like [GEdit](https://wiki.gnome.org/Apps/Gedit) in Ubuntu or [VIM](https://www.vim.org/) to modify the file?

2022-07-21 10:59 UTC, rohitpandey49 commented
> For `NOTICES.spdx`, there are several unnecessary changes. Can you please revert the file content and maybe use some basic editors like [GEdit](https://wiki.gnome.org/Apps/Gedit) in Ubuntu or [VIM](https://www.vim.org/) to modify the file?

Updated sir.

2022-07-22 09:02 UTC, GMishx approved these changes
Changes looks good.

2022-07-22 09:03 UTC, merged