feat(API): REST-API to initiate FOSSology maintenance
fossology/fossology pull request #2290
Opened 2022-08-11 07:12 UTC by dushimsam

Signed-off-by: dushimsam <dushsam100@gmail.com>

## Description
 A rest API to initiate FOSSology maintenance operations.

### Changes

1. Added a new controller file and the function to handle the logic in `MaintenanceController`.
2. Updated the file `maintagent.php` to be reusable by the outside callers.
3. Updated  the main file(`index.php`) by adding a new route `POST` `/maintenance`.
4. Updated the `openapi.yaml` file  to introduce a new API.

## How to test

1. Design a request as follows. 
2. The **options** property should contain the list of the keys whose operations are to be executed.
3. The **logsDate** property is the date from which to remove older gold files from repository.
4. The **goldDate** property is the date from which to remove older log files from repository.
3. Run the API.

![maintenance_operations](https://user-images.githubusercontent.com/66276301/184081603-2550d88c-e0d0-477b-9248-cc0569402def.png)

### Related Issue:
Fixes #2289
    
cc: @shaheemazmalmmd @GMishx

2022-08-12 12:31 UTC, GMishx requested changes

2022-08-12 12:31 UTC, GMishx commented on src/www/ui/api/Controllers/MaintenanceController.php
> +use maintagent;
Please remove undefined namespace.

2022-08-12 12:31 UTC, GMishx commented on src/www/ui/api/Controllers/MaintenanceController.php
> +      if (!array_key_exists($key, $maintain->getOptions())) {
Please store response from `$maintain->getOptions()` in a variable to reduce function calls.

2022-08-12 12:31 UTC, GMishx commented on src/www/ui/api/Controllers/MaintenanceController.php
> +        $returnVal = new Info(404, "KEY NOT FOUND!", InfoType::ERROR);
It will be better if user knows which key is not found :-)

2022-08-12 12:31 UTC, GMishx commented on src/www/ui/api/Controllers/MaintenanceController.php
> +    $body = $this->getParsedBody($request);
Please add a check here so only admins can run this job.

2022-08-12 12:31 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +            type: string
Please provide all possible options as an `enum`.

2022-08-14 07:19 UTC, dushimsam commented
Applied all chances. 
 
Let me know if there is any other thing to modify.

2022-08-24 17:29 UTC, GMishx requested changes
A small change required.

2022-08-24 17:29 UTC, GMishx commented on src/www/ui/api/Controllers/MaintenanceController.php
> +      $returnVal =  new Info(400, "Only admins can run this job.", InfoType::INFO);
Please use [401](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401) unauthorized request code.

2022-08-24 17:34 UTC, dushimsam commented on src/www/ui/api/Controllers/MaintenanceController.php
> +      $returnVal =  new Info(400, "Only admins can run this job.", InfoType::INFO);
yeap , done

2022-08-25 07:44 UTC, GMishx approved these changes
Changes look good.

2022-08-25 08:01 UTC, GMishx requested changes
While testing:

1. Providing `options` as an empty array schedules the maintenance agent without any action to preform. Which is not expected. In case the `options` is empty, a `400` response should be sent saying "At least one option should be selected".
2. In case of using `o` as the option ("Remove older gold files from repository.") and providing date using `logsDate` cause maintenance agent to fail with following message:
    ```
    /usr/local/etc/fossology/mods-enabled/maintagent/agent/maintagent: option requires an argument -- 'o'
    ```

Please check following code for option `o`, `l` and `t`
https://github.com/fossology/fossology/blob/460e6985b66e5de3fe0b1bda13bd6d77b72c7cb2/src/maintagent/ui/maintagent.php#L40-L53

2022-08-25 09:45 UTC, dushimsam commented
> While testing:
> 
> 1. Providing `options` as an empty array schedules the maintenance agent without any action to preform. Which is not expected. In case the `options` is empty, a `400` response should be sent saying "At least one option should be selected".
> 2. In case of using `o` as the option ("Remove older gold files from repository.") and providing date using `logsDate` cause maintenance agent to fail with following message:
>    ```
>    /usr/local/etc/fossology/mods-enabled/maintagent/agent/maintagent: option requires an argument -- 'o'
>    ```
> 
> Please check following code for option `o`, `l` and `t`
> 
> https://github.com/fossology/fossology/blob/460e6985b66e5de3fe0b1bda13bd6d77b72c7cb2/src/maintagent/ui/maintagent.php#L40-L53

Ok, cool I've found what's causing the problem.
Thanks to let me know.
releasing a clean PR in time.

2022-08-28 19:07 UTC, dushimsam commented
> While testing:
> 
> 1. Providing `options` as an empty array schedules the maintenance agent without any action to preform. Which is not expected. In case the `options` is empty, a `400` response should be sent saying "At least one option should be selected".
> 2. In case of using `o` as the option ("Remove older gold files from repository.") and providing date using `logsDate` cause maintenance agent to fail with following message:
>    ```
>    /usr/local/etc/fossology/mods-enabled/maintagent/agent/maintagent: option requires an argument -- 'o'
>    ```
> 
> Please check following code for option `o`, `l` and `t`
> 
> https://github.com/fossology/fossology/blob/460e6985b66e5de3fe0b1bda13bd6d77b72c7cb2/src/maintagent/ui/maintagent.php#L40-L53

Done could you review sir .

2022-09-02 10:24 UTC, GMishx approved these changes
Changes looks good.
Tested, working as expected.

2022-09-02 10:27 UTC, merged