fix(user-add.php): Fixed email can be blank but required
fossology/fossology pull request #2396
Opened 2023-03-19 21:33 UTC by Hero2323

the empty email checks and modified other email checks to function with an emtpy email field This fixes issue #2391

## Description

Fix "Email can be blank" but is actually required in the add user page.

### Changes

1. Removed `empty($Email)` check  
2. Modified the other two email checks to not give an error with the email field is empty

## How to test

Try to add a new user with the email field empty. Previously an error message used to be shown, now it doesn't

This fixes #2391

2023-03-21 14:42 UTC, GMishx requested changes

2023-03-21 19:24 UTC, Hero2323 commented on src/www/ui/user-add.php
>      if ($email_count > 0) {
I've fixed this issue by defining the `$email_count` before hand.

2023-06-09 04:42 UTC, GMishx approved these changes
Changes looks good.
@Hero2323 Please squash 3 commits into 1 to proceed with merge.

2023-06-09 04:53 UTC, GMishx approved these changes
Tested, working as expected.

2023-06-10 06:14 UTC, merged