feat(delete-job-endpoint): Added a delete job endpoint to the Fossolo…
fossology/fossology pull request #2407
Opened 2023-03-22 13:55 UTC by Hero2323

…gy API

It works based on Job ID and Job Queue ID. It also deletes Job Queues that depend ond the Job Queue to be deleted This fixes #1787

## Description

Added a delete endpoint to the fossology API

### Changes

Added a new endpoint `/jobs/{id}/{queue}` that deletes a job queue given the job queue and it's ID. It also deletes all queues depending on this job queue.

Also Added documentation to the `openapi.yaml` file and changed the version number.

Also modified the `index.php` file to add the endpoint to the list of routes.

## How to test

- Schedule a new Job
- Send a request to the localhost/repo/jobs/{id}/{queue} with the job id and job queue you'd like to delete

This fixes #1787

2023-05-31 11:52 UTC, GMishx requested changes
Minor change needed.

Please squash two commits into 1 for this PR.

2023-05-31 11:52 UTC, GMishx commented on src/www/ui/api/Controllers/JobController.php
> +      $Msg = "\"" . _("Killed by") . " " . $_SESSION[AUTH::USER_NAME] . "\"";
Please avoid using magic variable `$_SESSION` in API. Use following functions instead to get user object.

$userId = $this->restHelper->getUserId();
$userName = $this->restHelper->getUserDao()->getUserName($userId);

2023-06-09 16:49 UTC, Hero2323 commented
Added the optimizations, fixed the end of line white spaces and incorrect indentation.

2023-06-10 06:17 UTC, GMishx approved these changes
Changes looks good.

2023-06-28 06:53 UTC, GMishx approved these changes
Tested, working as expected.

2023-06-28 07:28 UTC, merged