feat(api): get main licenses assigned on an upload
fossology/fossology pull request #2465
Opened 2023-06-13 08:48 UTC by dushimsam

## Description

Added the API to get a list of the main licenses assigned on an upload.

### Changes

1. Added a new method in  `UploadController` to handle the logic.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/uploads/{id}/licenses/main`.
3. Updated the `openapi.yaml` file  to introduce a new API.

## How to test

Make a GET request on the endpoint: `/uploads/{id}/licenses/main`.

## Screenshots

![image](https://github.com/fossology/fossology/assets/66276301/c63dfd79-3b5e-466f-9b85-d30c3c1de614)

### Related Issue:
Fixes #2459   

    
cc: @shaheemazmalmmd @GMishx

<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2465"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2023-06-22 15:14 UTC, GMishx requested changes
Minor change needed.

2023-06-23 09:40 UTC, dushimsam commented on src/www/ui/api/documentation/openapi.yaml
> +                $ref: '#/components/schemas/License'
Done

2023-06-28 11:23 UTC, GMishx approved these changes
Changes looks good.

2023-06-28 11:26 UTC, GMishx approved these changes
Tested, working as expected.

2023-06-28 11:30 UTC, merged