feat(api): Delete Copyright for a File
fossology/fossology pull request #2478
Opened 2023-06-17 11:22 UTC by soham4abc

## Description

Deletes a copyright for a file using `/file/upload/<uploadId>/item/<ItemId>/copyright/<Hash>`

## Screenshot
![Screenshot from 2023-06-17 16-49-34](https://github.com/fossology/fossology/assets/63705023/4a0f395c-6627-414c-8e7f-87e2c7d7482d)

@GMishx 
@shaheemazmalmmd 

Please consider using the closing keyword if the pull request is proposed to
fix an issue already created in the repository
(https://help.github.com/articles/closing-issues-using-keywords/)

2023-06-29 11:00 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +          example: "INFO"
Isn't the response object exactly same as `Info` object?

2023-06-29 11:03 UTC, GMishx commented on src/www/ui/api/Controllers/CopyrightController.php
> +  public function DeleteFileCopyrights($request, $response, $args)
Please following coding guidelines.
```suggestion
  public function deleteFileCopyrights($request, $response, $args)
```

2023-06-29 13:22 UTC, soham4abc commented
Made the requested changes @GMishx 

Please do let me know if any more changes are required
Thank you!

2023-06-30 09:58 UTC, GMishx requested changes

2023-07-03 05:26 UTC, GMishx approved these changes
Changes looks good.
Needs test.

2023-07-03 05:28 UTC, GMishx approved these changes
Tested, working as expected.

2023-07-04 07:38 UTC, soham4abc commented
@GMishx should I be removing the test case as of now??

2023-07-05 05:04 UTC, GMishx commented
Sure @soham4abc , you can remove test cases. And please rebase the branch for merge.

2023-07-05 06:40 UTC, GMishx commented
Closing the branch as merged with 6015f625d917d2f2405cd16086e2516bbb8e8a99

2023-07-05 06:40 UTC, closed without merging