feat(api): Get list of bulk-history API
fossology/fossology pull request #2481
Opened 2023-06-18 20:14 UTC by dushimsam

## Description

Added the API to a get a list of the bulk history for a particular item.

### Changes

1. Added a new method in  `UploadTreeController` to handle the logic.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/uploads/{id}/items/{itemId}/bulk-scan`.
3. Updated the `openapi.yaml` file  to write the new API's documentation.

## How to test

Make a GET request on the endpoint: `GET` `/uploads/{id}/items/{itemId}/bulk-scan`.,

## Screenshots

![image](https://github.com/fossology/fossology/assets/66276301/ecdf3f89-8b34-497b-af29-5cced81e1ed9)

### Related Issue:
Fixes [#2472](https://github.com/fossology/fossology/issues/2472)

cc: @shaheemazmalmmd @GMishx

2023-06-29 11:28 UTC, GMishx requested changes
Minor changes.

2023-06-29 11:28 UTC, GMishx commented on src/www/ui/api/Controllers/UploadTreeController.php
> +    $this->container = $container;
Done in parent class.

2023-06-29 11:28 UTC, GMishx commented on src/www/ui/api/Controllers/UploadTreeController.php
> +      );
Would recommend creating a model for this complex response.

2023-06-29 11:28 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +          description: The job id associated with the bulk
No need to be in detail :-)
```suggestion
          description: The event id associated with the bulk
```

2023-06-29 11:28 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +          description: License Text
Scan reference text.

2023-06-29 11:28 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +          description: List of licenses added to the package
```suggestion
          description: List of license shortnames added to the scan
```

2023-06-29 11:28 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +          description: List of licenses removed from the package
```suggestion
          description: List of license shortnames removed from the scan
```

2023-06-29 11:31 UTC, GMishx commented
Tested, working as expected.

2023-07-03 14:34 UTC, dushimsam commented on src/www/ui/api/documentation/openapi.yaml
> +          description: List of licenses removed from the package
Updated the changes.

2023-07-05 09:41 UTC, GMishx approved these changes
Changes looks good.

2023-07-05 09:41 UTC, GMishx commented
@dushimsam , please rebase for merge.

2023-07-05 11:55 UTC, dushimsam commented
> @dushimsam , please rebase for merge.

Done

2023-07-05 15:29 UTC, merged