feat(api): REST API to get keywords and highlight-entries from content
fossology/fossology pull request #2484
Opened 2023-06-19 13:46 UTC by dushimsam

## Description

Added the API to get the index of the keywords and the highlight-entries from the given file's content.

### Changes

1. Added a new method in  `UploadController` to handle the logic.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/uploads/{id}/item/{itemId}/highlight`.
3. Updated the `openapi.yaml` file  to introduce a new API.

## How to test

Make a GET request on the endpoint: `/uploads/{id}/item/{itemId}/highlight`

## Screenshots
![image](https://github.com/fossology/fossology/assets/66276301/48b73325-764f-4e05-b917-afb2d9444fd2)

### Related Issue:
Fixes [#2459](https://github.com/fossology/fossology/issues/2459)

cc: @shaheemazmalmmd @GMishx

2023-06-29 11:50 UTC, GMishx requested changes

2023-06-29 11:50 UTC, GMishx commented on src/www/ui/api/Controllers/UploadTreeController.php
> +    $this->container = $container;
Already done in parent class.

2023-06-29 11:50 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +          type: integer
Please add description:
Start position of the highlight in file.

2023-06-29 11:50 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +          type: integer
Please add description:
End position of the highlight in file.

2023-06-29 11:50 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +          example: MD
Please add description:
Type of highlight.

With enum from `\Fossology\Lib\Data\Highlight`

2023-06-29 11:50 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +          example: 126
Please try to convert it into shortname (for consistency).

2023-06-29 11:50 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +          example: 0
Please add description:
Start of monk diff highlight (relative).

2023-06-29 11:50 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +          example: 53
Please add description:
End of monk diff highlight (relative).

2023-06-29 11:50 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +          example: "MIT: 'MIT License\n\nCopyright (c) <year> <copyright holders>'"
Please add description:
Tooltip text.

2023-07-03 15:23 UTC, dushimsam commented on src/www/ui/api/documentation/openapi.yaml
> +          example: "MIT: 'MIT License\n\nCopyright (c) <year> <copyright holders>'"
Updated the changes

2023-07-05 09:49 UTC, GMishx approved these changes
Changes looks good.

2023-07-05 09:49 UTC, GMishx commented
@dushimsam , please rebase for merge.

2023-07-05 12:07 UTC, dushimsam commented
Done

2023-07-07 09:07 UTC, GMishx commented
@dushimsam , please rebase again for merge.

2023-07-07 12:25 UTC, dushimsam commented
> @dushimsam , please rebase again for merge.

done @GMishx

2023-07-07 14:23 UTC, merged