feat(api): restore deleted copyrights
fossology/fossology pull request #2486
Opened 2023-06-21 06:29 UTC by soham4abc

## Description

Restores deleted copyright statements for a file

## How to test

send a `patch` request to the endpoint `file/upload/{uploadId}/item/{itemid}/copyright{copyrightHash}`

## Screenshots

![Screenshot from 2023-06-21 11-58-18](https://github.com/fossology/fossology/assets/63705023/47bd0d03-6cbc-4a81-a785-81c3571fd84c)

2023-07-05 09:59 UTC, GMishx requested changes

2023-07-05 09:59 UTC, GMishx commented on src/www/ui/api/Controllers/CopyrightController.php
> +    $this->CopyrightHist = $this->restHelper->getPlugin('ajax-copyright-hist');
Please rebase to resolve changes required in initializer.

2023-07-05 09:59 UTC, GMishx commented on src/www/ui/api/Controllers/CopyrightController.php
> +  public function RestoreFileCopyrights($request, $response, $args)
Please follow code style
```suggestion
   */
  public function restoreFileCopyrights($request, $response, $args)
```

2023-07-05 09:59 UTC, GMishx commented on src/www/ui/api/Controllers/CopyrightController.php
> +    try {
Please remove `try/catch` as discussed.

2023-07-05 09:59 UTC, GMishx commented on src/www/ui/api/Controllers/CopyrightController.php
> +      $UploadTreeTableName = $uploadDao->getUploadtreeTableName($uploadTreeId);
```suggestion
      $uploadTreeTableName = $uploadDao->getUploadtreeTableName($uploadTreeId);
```

2023-07-05 09:59 UTC, GMishx commented on src/www/ui/api/Controllers/CopyrightController.php
> +      }
Please move checks before accessing variables.

2023-07-05 09:59 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +  /file/upload{id}/item/{itemId}/copyright/{hash}:
Please update the path to be consistent with other endpoints.

2023-07-05 09:59 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +                type: integer
The header is irrelevant here.

2023-07-05 09:59 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +          example: "INFO"
Response is same as `Info`.

2023-07-05 15:35 UTC, GMishx requested changes

2023-07-05 15:35 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +             $ref: '#/components/schemas/SetCopyrightInfo'
```suggestion
              $ref: '#/components/schemas/SetCopyrightInfo'
```

2023-07-05 15:40 UTC, soham4abc commented
Re-based and updated lint change.

Please do have a look @GMishx

2023-07-10 07:02 UTC, GMishx requested changes

2023-07-10 07:02 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +             $ref: '#/components/schemas/SetCopyrightInfo'
Uh, seems like you removed one space instead of adding (as suggested).

2023-07-10 07:02 UTC, GMishx commented
@soham4abc please rebase the branch for merging.

2023-07-10 07:14 UTC, soham4abc commented
I have re-based the changes!!

Please do have a look @GMishx

2023-07-10 07:16 UTC, GMishx approved these changes
Changes looks good.

2023-07-10 07:20 UTC, GMishx approved these changes
Tested, working as expected.

2023-07-10 08:04 UTC, merged