feat(api): API to return total number of copyrights for a file
fossology/fossology pull request #2488
Opened 2023-06-21 17:19 UTC by soham4abc

## Description

This API returns the total number of copyrights for a UploadTree

## How to test
Send a `GET` request to `/file/upload/{UploadId}/item/{ItemId}/totalcopyrights`

##Screenshots
![Screenshot from 2023-06-21 22-47-51](https://github.com/fossology/fossology/assets/63705023/d0671ea0-53bd-4e2b-97ab-0345e54a3d87)

Fixes #2468

@shaheemazmalmmd Please do have a look as this was requested on priority basis.

2023-07-05 10:50 UTC, GMishx requested changes

2023-07-05 10:50 UTC, GMishx commented on src/www/ui/api/Controllers/CopyrightController.php
> +    $this->CopyrightHist = $this->restHelper->getPlugin('ajax-copyright-hist');
Please rebase to resolve issues here.

2023-07-05 10:50 UTC, GMishx commented on src/www/ui/api/Controllers/CopyrightController.php
> +    $UploadTreeTableName = $this->uploadDao->getUploadtreeTableName($uploadPk);
```suggestion
    $uploadTreeTableName = $this->uploadDao->getUploadtreeTableName($uploadPk);
```

2023-07-05 10:50 UTC, GMishx commented on src/www/ui/api/Controllers/CopyrightController.php
> +    try {
Please remove `try/catch` as discussed.

2023-07-05 10:50 UTC, GMishx commented on src/www/ui/api/Controllers/CopyrightController.php
> +      }
Please move checks before accessing the variables.

2023-07-05 10:50 UTC, GMishx commented on src/www/ui/api/Controllers/CopyrightController.php
> +      return $response->withJson($finalValue, 200);
Please use more efficient ways:
```suggestion
      return $response->withJson(["total_copyrights" => $returnVal[2]], 200);
```

2023-07-05 10:50 UTC, GMishx commented on src/www/ui/api/Controllers/CopyrightController.php
> +      return $response->withJson($finalValue, 200);
Even faster way is to move following lines to CopyrightDao as the function `getCopyrights()` also fetches other things from DB which are not required for this endpoint.

https://github.com/fossology/fossology/blob/fc89e1f3153d7c6eb088942ef6f0a2b44b58ade2/src/copyright/ui/ajax-copyright-hist.php#L288-L292

2023-07-05 10:50 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +  /file/upload/{id}/item/{ItemId}/totalcopyrights:
Please update path to be consistent with other endpoints.

2023-07-05 10:50 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +          description: Total copyright number
Such simple response body can directly be embedded in the response of endpoint.

2023-07-11 10:14 UTC, soham4abc commented
@GMishx I was planning to add query parameter to this endpoint so that we can actually get the number of total copyrights for both active and inactive types.

Should i go for it?

2023-07-11 11:11 UTC, soham4abc commented
> > @GMishx I was planning to add query parameter to this endpoint so that we can actually get the number of total copyrights for both active and inactive types.
> > Should i go for it?
> 
> Yes @soham4abc , it will be a good feature.

Done as per request sir.

Please do have a look!

2023-07-11 11:15 UTC, GMishx approved these changes
Changes looks good.

2023-07-11 11:29 UTC, GMishx approved these changes
Tested, working as expected.

2023-07-11 11:32 UTC, merged