feat(api): get a list of scanned licenses for an upload
fossology/fossology pull request #2495
Opened 2023-06-26 05:57 UTC by dushimsam

## Description

Added the API to retrieve a list of the scanned licenses for a given upload.

### Changes

1. Added a new method in  `UploadController` to handle the logic.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/uploads/{id}/licenses/scanned`.
3. Updated the `openapi.yaml` file  to introduce a new API.

## How to test

Make a GET request on the endpoint: `/uploads/{id}/licenses/scanned`.

## Screenshots

UI View:

![image](https://github.com/fossology/fossology/assets/66276301/34a4ae0d-1da0-403d-8252-1e746d851111)

API response:

![image](https://github.com/fossology/fossology/assets/66276301/3f9653eb-3533-4fa4-b0d6-f2e50d50de39)

### Related Issue:
Fixes [#2467](https://github.com/fossology/fossology/issues/2467)

cc: @shaheemazmalmmd @GMishx

2023-07-05 11:57 UTC, GMishx requested changes

2023-07-05 11:57 UTC, GMishx commented on src/www/ui/api/Controllers/UploadController.php
> +  private $agentNames = AgentRef::AGENT_LIST;
Would suggest to use `AgentRef::AGENT_LIST` directly wherever needed to make it easy to identify in future.

2023-07-05 11:57 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +          example: Apache-2.0
Please call it shortname.

2023-07-05 11:57 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +            unique:
What is this property? Sorry I cannot understand it.

2023-07-05 11:57 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +            rf_pk:
It should be license id

2023-07-05 11:57 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +            spdx_id:
```suggestion
            spdx_name:
```

2023-07-07 12:43 UTC, dushimsam commented on src/www/ui/api/documentation/openapi.yaml
> +            spdx_id:
updated the changes @GMishx

2023-07-10 07:48 UTC, GMishx requested changes
A minor change needed.

2023-07-10 07:48 UTC, GMishx commented on src/www/ui/api/Controllers/UploadController.php
> +        ];
Please make a model class for the response.

2023-07-26 05:17 UTC, GMishx approved these changes
Changes looks good.

2023-07-26 05:21 UTC, GMishx approved these changes
Tested, working as expected.

2023-07-26 10:09 UTC, GMishx commented
Some indentation issues @dushimsam 
https://github.com/fossology/fossology/actions/runs/5667337430/job/15355877681?pr=2495#step:4:204

2023-07-26 10:23 UTC, GMishx commented
Sorry to disturb again but can you please rebase the branch for merging @dushimsam ?

2023-07-26 10:44 UTC, dushimsam commented
> Sorry to disturb again but can you please rebase the branch for merging @dushimsam ?

No worries @GMishx , let me do it

2023-07-28 07:26 UTC, merged