feat(api): File info API
fossology/fossology pull request #2496
Opened 2023-06-26 10:57 UTC by soham4abc

## Description

API endpoint to get info for a file

## How to test
Send a get request to `/file/upload/{UploadId}/item/{ItemId}/info`

## Screenshots
![image](https://github.com/fossology/fossology/assets/63705023/87455744-0413-48cc-ba2a-8431d93d6c34)

closes #2493

@shaheemazmalmmd @GMishx

2023-07-10 08:03 UTC, GMishx requested changes
Seeing the screenshot attached, would recommend following changes:
1. `view_info`:
  1. can extend the `Hash` model object as it already contains the checksums and file size.
  2. No need of different size calculations, the size in bytes stored in `Hash` can be used to calculate them.
  3. Change `filePfileId` to `pfileId`.
2. `meta_info`:
  1. Remove `file` from the beginning of keys.
  2. I believe `fileInfo` and `scanossInfo` as booleans? Please check if so and translate `1 => true`, `0 => false`.

Try uploading this small `deb` file and run the package analysis agent on it to get more info on the page.
At the same time, try running the `scanoss` agent on FOSSology or atarashi to get some match info in Info page.

https://ftp.debian.org/debian/pool/main/l/lsb/lsb-release_11.1.0_all.deb

2023-07-24 05:52 UTC, GMishx commented on src/www/ui/api/Controllers/FileInfoController.php
> +    $this->restHelper = $container->get('helper.restHelper');
```suggestion
    $this->clearingDao = $this->container->get('dao.clearing');
    $this->licenseDao = $this->container->get('dao.license');
    $this->uploadDao = $this->container->get('dao.upload');
    $this->restHelper = $this->container->get('helper.restHelper');
```

2023-07-24 05:52 UTC, GMishx commented on src/www/ui/api/Controllers/FileInfoController.php
> +      return $response->withJson($finalValue, 200);
Please fix indentation.

2023-07-24 05:52 UTC, GMishx commented on src/www/ui/api/Controllers/FileInfoController.php
> +      return $response->withJson($finalValue, 200);
Ummm.. Does not seem to have been resolved.

2023-07-24 05:57 UTC, GMishx requested changes

2023-07-24 05:57 UTC, GMishx commented on src/www/ui/api/Controllers/FileInfoController.php
> +    $this->restHelper = $container->get('helper.restHelper');
Setting container is already done in parent class.
```suggestion
    $this->clearingDao = $this->container->get('dao.clearing');
    $this->licenseDao = $this->container->get('dao.license');
    $this->uploadDao = $this->container->get('dao.upload');
    $this->restHelper = $this->container->get('helper.restHelper');
```

2023-07-24 05:58 UTC, GMishx commented
Tested, working as expected.

2023-07-24 06:58 UTC, soham4abc commented
Response for the provided .deb file

Please do have a look at it and we can discuss further changes required!
![image](https://github.com/fossology/fossology/assets/63705023/658ab40f-3666-496d-b5ea-925269035a26)

2023-07-26 05:28 UTC, GMishx requested changes

2023-07-26 05:28 UTC, GMishx commented on src/www/ui/api/Controllers/FileInfoController.php
> +    $this->container = $container;
Parent class initializer does this for you. No need to override it. Please remove the line.

https://github.com/fossology/fossology/blob/3d6195aeff303a01511b5b7662e138f059557f16/src/www/ui/api/Controllers/RestController.php#L52

2023-07-26 05:28 UTC, GMishx commented on src/www/ui/api/index.php
> +
Since the endpoint is move to `/uploads/{id}/item/{itemId}/info`, shouldn't this be removed as well?

2023-07-26 05:29 UTC, GMishx commented
> Response for the provided .deb file
> 
> Please do have a look at it and we can discuss further changes required! ![image]

pkgagent does not seem to work correctly now. Let us not bother much about its output as people rarely use it. We can fix it later.

2023-07-26 05:54 UTC, soham4abc commented
> > Response for the provided .deb file
> > Please do have a look at it and we can discuss further changes required! ![image]
> 
> pkgagent does not seem to work correctly now. Let us not bother much about its output as people rarely use it. We can fix it later.

Sure!!

2023-07-26 07:10 UTC, GMishx requested changes

2023-07-26 07:10 UTC, GMishx commented on src/www/ui/api/Controllers/FileInfoController.php
> +
Unused property. Please remove.

2023-07-26 07:14 UTC, GMishx approved these changes
Changes looks good.

2023-07-26 07:46 UTC, merged