feat(api): get edited licenses list
fossology/fossology pull request #2498
Opened 2023-06-26 14:46 UTC by dushimsam

## Description

Added the API to retrieve a list of the edited licenses for a given upload.

### Changes

1. Added a new method in  `UploadController` to handle the logic.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/uploads/{id}/licenses/edited`.
3. Updated the `openapi.yaml` file  to introduce a new API.

## How to test

Make a GET request on the endpoint: `/uploads/{id}/licenses/edited`.

## Screenshots

**UI View:**

![image](https://github.com/fossology/fossology/assets/66276301/a6d62fa2-59f8-481a-8731-b2068c5145a0)

**API response:**

![image](https://github.com/fossology/fossology/assets/66276301/26c0f91e-104d-4cd1-b756-51d3bf869da2)

### Related Issue:
Fixes [#2467](https://github.com/fossology/fossology/issues/2467)

cc: @shaheemazmalmmd @GMishx

<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2495"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2023-07-10 09:40 UTC, GMishx requested changes

2023-07-10 09:40 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +        name:
Please call it `shortName`.

2023-07-10 09:41 UTC, GMishx commented
Tested, working as expected.

2023-07-10 14:15 UTC, dushimsam commented on src/www/ui/api/documentation/openapi.yaml
> +        name:
Done

2023-07-24 05:59 UTC, GMishx approved these changes
Changes looks good.

2023-07-26 05:16 UTC, merged