feat(api): conf info for upload
fossology/fossology pull request #2505
Opened 2023-06-27 06:27 UTC by soham4abc

## Description

This endpoint provides us full conf information as a response for an Upload. 

## How to test

Send a GET request to `/file/upload/{UploadId}/item/{UploadId}/conf`

## Screenshots
![image](https://github.com/fossology/fossology/assets/63705023/b9274cb7-cf7c-4770-9b39-d61966d15b95)

Closes #2504

2023-07-10 10:11 UTC, GMishx requested changes

2023-07-10 10:11 UTC, GMishx commented on src/www/ui/api/Controllers/ConfController.php
> +      return $response->withJson($response_view, 200);
Use following JSON format for the same:
```json
{
  "reviewed": "Some Name",
  "footer": "Some Organization",
  "reportRel": "Some release date",
  "community": "Community name",
  "component": "Component name",
  "version": "1.2.3",
  "releaseDate": "12\\/05\\/2018",
  "sw360Link": "NA",
  "componentType": "package-url",
  "componentId": "pkg:npm\\/30-seconds-of-code@1.2.3",
  "generalAssesment": "Some assessment test",
  "gaAdditional": "NA",
  "gaRisk": "No additional information\\/violations found for the package.",
  "gaCheckbox": "unchecked,unchecked,unchecked,unchecked,unchecked,unchecked,unchecked,unchecked,unchecked",
  "spdxSelection": "checked,unchecked",
  "excludedObligations": {
    "Obligation 1": [
      "MIT",
      "GPL-3.0-only"
    ]
  },
  "department": "FOSSology Generation",
  "depNotes": "NA",
  "exportNotes": "NA",
  "copyrightNotes": "NA",
  "unifiedColumns": {"assessment":{"Assessment Summary":"on"},"compliancetasks":{"Required license compliance tasks":"on"},"acknowledgements":{"Acknowledgements":"on"},"exportrestrictions":{"Export Restrictions":"on"},"intellectualProperty":{"Patent Relevant Statements":"on"},"notes":{"Notes":"on"},"scanresults":{"Results of License Scan":"on"},"mainlicenses":{"Main Licenses":"on"},"redlicense":{"Other OSS Licenses (red) - Do not Use Licenses":"on"},"yellowlicense":{"Other OSS Licenses (yellow) - additional obligations to common rules (e.g. copyleft)":"on"},"whitelicense":{"Other OSS Licenses (white) - only common rules":"on"},"overviewwithwithoutobligations":{"Overview of All Licenses with or without Obligations":"on"},"copyrights":{"Copyrights":"on"},"copyrightsuf":{"Copyrights (User Findings)":"on"},"bulkfindings":{"Bulk Findings":"on"},"licensenf":{"Non-Functional Licenses":"on"},"irrelevantfiles":{"Irrelevant Files":"on"},"dnufiles":{"Do not use Files":"on"},"changelog":{"Clearing Protocol Change Log":"on"}},
  "globalDecision": false
}
```

Additional notes:
1. `componentType`: Use map from class \Fossology\Lib\Data\Package\ComponentType
2. `excludedObligations`: Can be an object, `null` or empty array `[]`
3. `unifiedColumns`: It is an object with key: "report conf section id" and value: "{display text, on/off}"
4. `globalDecision`: It is a boolean.

2023-07-14 17:31 UTC, soham4abc commented
new response format:

![image](https://github.com/fossology/fossology/assets/63705023/2e8caba0-5327-44fc-a095-c807fff54559)

2023-07-24 06:14 UTC, GMishx requested changes

2023-07-24 06:14 UTC, GMishx commented on src/www/ui/api/Controllers/ConfController.php
> +    $this->restHelper = $container->get('helper.restHelper');
Container is set in parent class.

```suggestion
    parent::__construct($container);
    $this->clearingDao = $this->container->get('dao.clearing');
    $this->licenseDao = $this->container->get('dao.license');
```

2023-07-24 06:14 UTC, GMishx commented on src/www/ui/api/Controllers/ConfController.php
> +    $this->uploadDao = $container->get('dao.upload');
```suggestion
    $this->uploadDao = $this->restHelper->getUploadDao();
```

2023-07-24 06:14 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +    confResponse:
Please following naming convention
```suggestion
    ConfResponse
```

2023-07-24 06:14 UTC, GMishx commented on src/www/ui/api/Models/Conf.php
> +      'unifiedColumns' => $this->data["ri_unifiedcolumns"],
Translate this data back as an array. It currently renders as a JSON string.

2023-07-24 06:18 UTC, GMishx requested changes

2023-07-24 06:18 UTC, GMishx commented on src/www/ui/api/Models/Conf.php
> +      'excludedObligations' => $this->data["ri_excluded_obligations"],
Translate this as well from JSON string to array. See comment https://github.com/fossology/fossology/pull/2505#discussion_r1258024534

2023-07-26 05:34 UTC, GMishx requested changes

2023-07-26 05:34 UTC, GMishx commented on src/www/ui/api/Controllers/ConfController.php
> +
No need to re-declare the property again. Please remove.

2023-07-26 05:34 UTC, GMishx commented on src/www/ui/api/Models/Conf.php
> +      'excludedObligations' => $this->data["ri_excluded_obligations"],
I see no code changes here. Why the conversation was marked as resolved?

2023-07-26 05:34 UTC, GMishx commented on src/www/ui/api/Models/Conf.php
> +      'unifiedColumns' => $this->data["ri_unifiedcolumns"],
I see no code changes here. Why the conversation was marked as resolved?

2023-07-26 06:03 UTC, soham4abc commented
@GMishx I am not able to understand how do I translate the response to an array from JSON string. Can you provide some insight and information regarding this please?

2023-07-26 07:12 UTC, GMishx commented
> @GMishx I am not able to understand how do I translate the response to an array from JSON string. Can you provide some insight and information regarding this please?

So please ask question, don't simply mark discussion as resolved.

[json_decode()](https://www.php.net/manual/en/function.json-decode.php) is your friend.

2023-07-26 07:14 UTC, soham4abc commented
> 

Sure!!

My bad, I thought having it under array() would resolve the issue but it was a wrong approach.

Thanks for the information!!! 

@GMishx

2023-07-26 07:28 UTC, soham4abc commented
> > @GMishx I am not able to understand how do I translate the response to an array from JSON string. Can you provide some insight and information regarding this please?
> 
> So please ask question, don't simply mark discussion as resolved.
> 
> [json_decode()](https://www.php.net/manual/en/function.json-decode.php) is your friend.

I tried to use json_decode() method but it says it's already an array.

![image](https://github.com/fossology/fossology/assets/63705023/9141f424-b5c6-4cca-a794-70120e65d848)

And the returned result is `NULL`.

2023-07-26 10:13 UTC, GMishx commented
> > > @GMishx I am not able to understand how do I translate the response to an array from JSON string. Can you provide some insight and information regarding this please?
> > 
> > 
> > So please ask question, don't simply mark discussion as resolved.
> > [json_decode()](https://www.php.net/manual/en/function.json-decode.php) is your friend.
> 
> I tried to use json_decode() method but it says it's already an array.
> 
> ![image](https://user-images.githubusercontent.com/63705023/256151084-9141f424-b5c6-4cca-a794-70120e65d848.png)
> 
> And the returned result is `NULL`.

Ummm, why are you decoding an array?

I expected to decode just the `ri_excluded_obligations` and `ri_unifiedcolumns`.

2023-07-26 10:29 UTC, soham4abc commented
> > > > @GMishx I am not able to understand how do I translate the response to an array from JSON string. Can you provide some insight and information regarding this please?
> > > 
> > > 
> > > So please ask question, don't simply mark discussion as resolved.
> > > [json_decode()](https://www.php.net/manual/en/function.json-decode.php) is your friend.
> > 
> > 
> > I tried to use json_decode() method but it says it's already an array.
> > ![image](https://user-images.githubusercontent.com/63705023/256151084-9141f424-b5c6-4cca-a794-70120e65d848.png)
> > And the returned result is `NULL`.
> 
> Ummm, why are you decoding an array?
> 
> I expected to decode just the `ri_excluded_obligations` and `ri_unifiedcolumns`.

I'm, Sorry I completely misunderstood the requested change.

Made the changes and pushed as of now

The current response:

![image](https://github.com/fossology/fossology/assets/63705023/42e9168a-b252-429d-a0d2-ea509d7bc314)

2023-07-31 05:40 UTC, GMishx commented on src/www/ui/api/Controllers/ConfController.php
> +
Reminder @soham4abc

2023-07-31 05:42 UTC, GMishx requested changes

2023-07-31 05:42 UTC, GMishx commented on src/www/ui/api/Controllers/ConfController.php
> + SPDX-FileCopyrightText: © 2018 Siemens AG
Please remove invalid copyright text.

2023-07-31 05:42 UTC, GMishx commented on src/www/ui/api/Controllers/ConfController.php
> +
Please remove as requested.

2023-07-31 05:42 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +              example: display text
```suggestion
                - on
                - off
              example: on
```

2023-07-31 05:42 UTC, GMishx commented
Tested, working as expected.

2023-07-31 06:17 UTC, soham4abc commented
Made the changes as per request. 
Please do have a look!!

Thank you!

2023-08-08 05:55 UTC, GMishx approved these changes
Changes looks good.

2023-08-08 05:58 UTC, merged