feat(api): Add, edit & delete license decision
fossology/fossology pull request #2509
Opened 2023-06-29 13:50 UTC by dushimsam

## Description

Added the API to handle add, edit, and delete of the license decisions in one request.

### Changes

1. Added a new method in  `UploadTreeController` to handle the logic.
2. Created the method in `UploadTreeController` for handling add, edit and delete of the items given in the request body.
3. Updated  the main file(`index.php`) by adding a new route `PUT` `/uploads/{id}/item/{itemId}/licenses`.
4. Updated the `openapi.yaml` file  to write the new API's documentation.

## How to test

Make a PUT request on the endpoint: ``/uploads/{id}/item/{itemId}/licenses``,

## Screenshots

### Request
![image](https://github.com/fossology/fossology/assets/66276301/345c9f4a-1376-4f1f-988e-8436b8c29c14)

### Response
![image](https://github.com/fossology/fossology/assets/66276301/16931d5c-e649-4be1-a6e8-04b1e4d7efce)

### Related Issue:
Fixes #2459 

    
cc: @shaheemazmalmmd @GMishx

2023-07-24 11:26 UTC, GMishx requested changes
Minor changes.

2023-07-24 11:26 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +
Please remove whitespaces.

2023-07-24 11:26 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +            example: "This is a license decision comment"
Please fix the indentation.

2023-07-24 11:34 UTC, GMishx commented
Tested, working as expected.

2023-07-24 15:28 UTC, dushimsam commented on src/www/ui/api/documentation/openapi.yaml
> +
Done

2023-07-26 06:58 UTC, GMishx approved these changes
Changes looks good.

2023-08-09 11:01 UTC, merged