feat(api): Get all licenses-admin acknowlegments
fossology/fossology pull request #2512
Opened 2023-07-03 16:28 UTC by dushimsam

## Description

Added the API to retrieve a list of the licenses' admin acknowledgments.

### Changes

1. Added a new method in  `LicenseController` to build the functionality.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/licenses/adminacknowlegments`.
4. Updated the `openapi.yaml` file  to write the new API's documentation.

## How to test

Make a GET request on the endpoint:  `/licenses/adminacknowlegments`,

## Screenshots

![image](https://github.com/fossology/fossology/assets/66276301/53743f5a-ffec-4f51-a3e4-16d98113629d)

### Related Issue:
Fixes #2511 

    
cc: @shaheemazmalmmd @GMishx

<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2509"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2023-07-24 11:38 UTC, GMishx requested changes
Minor change.

2023-07-24 11:38 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +        la_pk:
Would suggest calling it ID.
```suggestion
        id:
```

2023-07-24 11:41 UTC, GMishx commented
Tested, working as expected.

2023-07-24 15:38 UTC, dushimsam commented on src/www/ui/api/documentation/openapi.yaml
> +        la_pk:
Done

2023-07-26 06:59 UTC, GMishx approved these changes
Changes looks good.

2023-07-26 06:59 UTC, merged