feat(api): get-all standard comments
fossology/fossology pull request #2517
Opened 2023-07-04 12:54 UTC by dushimsam

## Description

Added the API to retrieve a list of the standard comments.

### Changes

1. Added a new method in  `LicenseController` to build the functionality.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/licenses/stdcomments`.
4. Updated the `openapi.yaml` file  to write the new API's documentation.

## How to test

Make a GET request on the endpoint:  `/licenses/stdcomments`,

## Screenshots

![image](https://github.com/fossology/fossology/assets/66276301/e86abcf1-2d91-4d4c-8575-b9c558655c0e)

### Related Issue:
Fixes #2511 

    
cc: @shaheemazmalmmd @GMishx

2023-07-31 05:50 UTC, GMishx requested changes

2023-07-31 05:50 UTC, GMishx commented on src/www/ui/api/Controllers/LicenseController.php
> +    }
Get for this endpoint should be allowed for all users as it is used at file clearing page as well.

2023-07-31 05:50 UTC, GMishx commented on src/www/ui/api/Controllers/LicenseController.php
> +    }
![snap](https://github.com/fossology/fossology/assets/18077542/ec105cb7-5552-412c-8f82-9015999d80f1)

2023-07-31 05:50 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +                $ref: '#/components/schemas/Info'
No need to document `500` here. It is covered by `defaultResponse`.

2023-07-31 05:50 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +        lsc_pk:
Should be called as `id`.

2023-07-31 05:52 UTC, GMishx commented
Tested, working as expected.

2023-08-09 11:03 UTC, GMishx approved these changes
Changes looks good.

2023-08-09 11:05 UTC, GMishx commented
@dushimsam , please rebase for merge.

2023-08-14 07:32 UTC, dushimsam commented
Done

2023-08-28 05:20 UTC, merged