feat(api): Get Customise page data
fossology/fossology pull request #2520
Opened 2023-07-04 15:33 UTC by soham4abc

## Description

This PR introduces an endpoint to fetch data for the customize page from admin panel 

THIS PR IS WIP and to be updated according to the requirements.

## How to test

send a `GET` request to `localhost/repo/api/v1/customise`

## Screenshots
![Screenshot from 2023-07-04 20-50-06](https://github.com/fossology/fossology/assets/63705023/693daddd-2383-47e3-8738-f168cdbdaec9)

closes #2519

2023-07-07 09:52 UTC, soham4abc commented
![image](https://github.com/fossology/fossology/assets/63705023/6c501afe-8a90-41af-8fa0-780ee55ef913)
Updated response for `/customise` endpoint.

Please do have a look @GMishx

2023-07-07 09:53 UTC, soham4abc commented
This PR also updates the Database schema to update description of `vartypes` in `sysconfig` table
@GMishx

2023-07-10 11:43 UTC, GMishx requested changes

2023-07-10 11:43 UTC, GMishx commented on src/www/ui/api/Controllers/CustomiseController.php
> +        '6' => 'boolean'
Please use consistent quote types.

2023-07-10 11:43 UTC, GMishx commented on src/www/ui/api/Controllers/CustomiseController.php
> +      return ($response->withJson($finalVal, 200));
```suggestion
      return $response->withJson($finalVal, 200);
```

2023-07-10 11:43 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +              type: string
Please document different types as enum

2023-07-10 11:43 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +              type: integer
```suggestion
              type: string
```

2023-07-10 11:43 UTC, GMishx commented on src/www/ui/core-schema.dat
> +  $Schema["TABLE"]["sysconfig"]["vartype"]["DESC"] = "COMMENT ON COLUMN \"sysconfig\".\"vartype\" IS 'variable type.  1=int, 2=text, 3=textarea, 4=password, 5=dropdown 6=boolean'";
```suggestion
  $Schema["TABLE"]["sysconfig"]["vartype"]["DESC"] = "COMMENT ON COLUMN \"sysconfig\".\"vartype\" IS 'variable type.  1=int, 2=text, 3=textarea, 4=password, 5=dropdown, 6=boolean'";
```

2023-07-10 15:35 UTC, soham4abc commented on src/www/ui/admin-config.php
> +  function getConfigData()
So, should I be creating a separate DAO for the admin functions named AdminDAO? and create a method there itself to get the config data in the desired output format?

2023-07-12 12:52 UTC, soham4abc commented
PR updated as per meeting discussions on 12/07/2023

@GMishx Please do have a look

2023-07-31 06:17 UTC, GMishx requested changes

2023-07-31 06:17 UTC, GMishx commented on src/lib/php/Dao/SysConfigDao.php
> +    return (pg_fetch_all($result));
Use modern DBManager.
```suggestion
    $sql = "SELECT * FROM sysconfig ORDER BY group_name, group_order";
    return $this->dbManager->getRows($sql);
```

2023-07-31 06:17 UTC, GMishx commented on src/lib/php/Dao/SysConfigDao.php
> +  public function getCustomiseData($data)
Please document in docstring what `$data` should look like.

2023-07-31 06:17 UTC, GMishx commented on src/lib/php/Dao/SysConfigDao.php
> +      } else {
Keeping the return type consistent as string will help consumer of the endpoint by using single class to read the data.

2023-07-31 06:17 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +
```suggestion

```

2023-07-31 06:17 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +
This structure no longer matches the current response. Please update.

2023-07-31 08:07 UTC, soham4abc commented
Made the requested changes. Please do have a look @GMishx 
Thank you!

2023-08-08 06:12 UTC, GMishx requested changes

2023-08-08 06:12 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +        Returns the admin configureation data from the server
```suggestion
      summary: Get the Admin configuration data
      description: >
        Returns the admin configuration data from the server
```

2023-08-08 06:12 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +      description: Admin customise ddata object
```suggestion
      description: Admin customise data object
```

2023-08-08 06:12 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +
Small formatting changes needed.
```suggestion
          - boolean
        label:
          description: field label
          type: string
        group_name:
          description: group name for the field
          type: string
        group_order:
          description: group order of the field
          type: integer
        option_value:
          description: If type is 'dropdown', provide options in format op1{val1}|op2{val2}|...
          type: string

```

2023-08-08 06:35 UTC, GMishx approved these changes
Changes looks good.

2023-08-08 06:35 UTC, merged