feat(api): Get the database contents for the dashboard overview
fossology/fossology pull request #2530
Opened 2023-07-07 14:12 UTC by dushimsam

## Description

Added the API to retrieve the database contents with corresponding statuses.

### Changes

1. Added a new method in  `OverviewController` to build the functionality.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/overview/database/contents`.
4. Updated the `openapi.yaml` file  to write the new API's documentation.

## How to test

Make a GET request on the endpoint:  `/overview/database/contents`,

## Screenshots

![image](https://github.com/fossology/fossology/assets/66276301/1a5eb645-7aba-4892-9832-e3258d2270a2)

![image](https://github.com/fossology/fossology/assets/66276301/fc5b84c6-a781-4a95-ab6c-3a8bf4921fab)

### Related Issue:
Fixes #2523 
    
cc: @shaheemazmalmmd @GMishx

2023-08-09 10:57 UTC, GMishx requested changes
Minor change needed.

2023-08-09 10:57 UTC, GMishx commented on src/www/ui/api/Controllers/OverviewController.php
> +      $error = new Info(403, "Only admin can edit main licenses.", InfoType::ERROR);
Wrong error message. Please update.

2023-08-14 08:07 UTC, dushimsam commented on src/www/ui/api/Controllers/OverviewController.php
> +      $error = new Info(403, "Only admin can edit main licenses.", InfoType::ERROR);
Done

2023-08-28 07:27 UTC, GMishx approved these changes
Changes looks good.

2023-09-26 06:17 UTC, merged