feat(api): Get the summary statistics for all Jobs
fossology/fossology pull request #2537
Opened 2023-07-09 16:17 UTC by dushimsam

## Description

Added the API to retrieve the server jobs for the Admin Dashboard overview.

### Changes

1. Added a new method in  `JobController` to build the functionality.
2. Updated  the main file(`index.php`) by adding a new route `GET` `/jobs/dashboard/statistics`.
4. Updated the `openapi.yaml` file  to write the new API's documentation.

## How to test

Make a GET request on the endpoint:  `/jobs/dashboard/statistics`,

## Screenshots

![image](https://github.com/fossology/fossology/assets/66276301/7b0e513c-0ae0-4d7a-868f-0101c361623d)
![image](https://github.com/fossology/fossology/assets/66276301/94620102-8c0c-467d-924e-d21bc6df66e3)

### Related Issue:
Fixes #2523 
    
cc: @shaheemazmalmmd @GMishx

2023-08-28 09:23 UTC, GMishx requested changes

2023-08-28 09:23 UTC, GMishx commented on src/www/ui/api/documentation/openapi.yaml
> +        fired_jobs:
Please use camelCasing for the name.

2023-08-28 20:22 UTC, dushimsam commented on src/www/ui/api/documentation/openapi.yaml
> +        fired_jobs:
Changes updated

2023-08-29 10:43 UTC, GMishx approved these changes
Changes looks good.

2023-08-29 10:47 UTC, GMishx approved these changes
Tested, working as expected.

2023-08-29 10:47 UTC, merged