fix(php): remove & to be compatible with PHP 8
fossology/fossology pull request #2605
Opened 2023-10-12 16:55 UTC by vargenau

## Description

Fix old PHP syntax to be compatible with PHP 8.

### Changes

Remove ```&``` in ```array_push``` and before ```new```.

2023-10-16 04:33 UTC, GMishx requested changes
Improvement suggestions.

2023-10-16 04:33 UTC, GMishx commented on utils/freshmeat/Classes/FreshmeatRdfs.php
>                     );
Can be optimized for single insertion by using array operator as bellow:
```suggestion
        $this->project_info["$project->projectname_short"][] = $verdata->latest_release_version;
```

2023-10-16 04:33 UTC, GMishx commented on utils/freshmeat/lib_projxml.h.php
> +      array_push($project, $line);
Can be optimized for single insertion:
```suggestion
      $project[] = $line;
```

2023-10-16 04:33 UTC, GMishx commented on utils/freshmeat/lib_projxml.h.php
> +    array_push($project, $line);
Can be optimized for single insertion:
```suggestion
    $project[] = $line;
```

2023-10-16 12:37 UTC, vargenau commented
Suggestions implemented.

2023-10-18 07:44 UTC, GMishx commented on utils/freshmeat/lib_projxml.h.php
> +    array_push($project, $line);
Oops, looks like you missed this suggestion :-)

2023-10-18 09:08 UTC, vargenau commented
@GMishx
Done

2023-10-20 05:04 UTC, GMishx approved these changes

2023-10-20 05:04 UTC, merged