fix(php): Factor common code
fossology/fossology pull request #2607
Opened 2023-10-13 11:52 UTC by vargenau

## Description

Some code is duplicated.

### Changes

Factor common code.
Remove useless local variables.

2023-10-13 11:58 UTC, vargenau commented
Use master for these 4 files.

2023-10-16 05:00 UTC, GMishx requested changes

2023-10-16 13:03 UTC, vargenau commented
Indentation fixed.

2023-10-18 07:47 UTC, GMishx requested changes
Needs changes at 2 more locations.

2023-10-18 07:47 UTC, GMishx commented on src/ununpack/ui/ui-reunpack.php
> +        pg_free_result($result);
Please fix the indentation
```suggestion
    if (empty($row)) {
      $result = pg_query($PG_CONN, $SQLInsert);
      DBCheckResult($result, $SQLInsert, __FILE__, __LINE__);
      $row = pg_fetch_assoc($result);
      pg_free_result($result);
      $SQLcheck = "SELECT job_pk FROM job WHERE job_upload_fk = '$uploadpk'"
        . " AND job_name = '$Job_name' AND job_user_fk = '$user_fk';";
      $result = pg_query($PG_CONN, $SQLcheck);
      DBCheckResult($result, $SQLcheck, __FILE__, __LINE__);
      $row = pg_fetch_assoc($result);
      pg_free_result($result);
```

2023-10-18 09:02 UTC, vargenau commented
@GMishx 
Indentation fixed

2023-10-20 05:05 UTC, GMishx approved these changes

2023-10-20 05:05 UTC, merged