fix(php): add function return type
fossology/fossology pull request #2612
Opened 2023-10-18 13:57 UTC by vargenau

## Description

Functions have no return type.

### Changes

Add function return type.

2023-10-27 11:22 UTC, GMishx requested changes

2023-10-27 11:22 UTC, GMishx commented on src/lib/php/common-menu.php
Can add return type `:string` to `MenuPage()`.

2023-10-27 11:22 UTC, GMishx commented on src/lib/php/common-menu.php
Type `:string` to `MenuEndlessPage()`.

2023-10-27 11:22 UTC, GMishx commented on src/lib/php/common-parm.php
Can add return type `:string` to `Traceback()`.

2023-10-27 11:22 UTC, GMishx commented on src/lib/php/common-parm.php
Type `:string` to `Traceback_uri()`.

2023-10-27 11:22 UTC, GMishx commented on src/lib/php/common-parm.php
Type `:string` to `Traceback_parm()`.

2023-10-27 11:22 UTC, GMishx commented on src/lib/php/common-parm.php
Type `:string` to `Traceback_dir()`.

2023-10-27 11:22 UTC, GMishx commented on src/lib/php/common-perms.php
> +function GetUsersGroups($user_pk=''): array
The function does not always return. So, the value can also be null.
```suggestion
function GetUsersGroups($user_pk=''): ?array
```

2023-10-27 11:22 UTC, GMishx commented on src/lib/php/common-perms.php
Can add return type `: ?string` to `DeleteGroup()`.

2023-10-27 11:22 UTC, GMishx commented on src/lib/php/common-plugin.php
Can set the return type to `:string|int` for `plugin_find_id()`.

2023-10-27 11:22 UTC, GMishx commented on src/lib/php/common-plugin.php
Type `:?Plugin` to `plugin_find()`.

2023-10-27 11:22 UTC, GMishx commented on src/lib/php/common-scheduler.php
Can add type `: false|string` to `fo_scheduler_read()`.

2023-10-27 11:22 UTC, GMishx commented on src/lib/php/common-scheduler.php
Type `: false|int` to `fo_scheduler_write()`.

2023-10-27 11:22 UTC, GMishx commented on src/lib/php/common-scheduler.php
Type `: ?array` to `GetRunnableJobList()`.

2023-10-27 11:22 UTC, GMishx commented on src/lib/php/common-string.php
Can add type `: string` to `convertToUTF8()`.

2023-10-27 11:22 UTC, GMishx commented on src/lib/php/common-string.php
Type `: false|string` to `tryConvertToUTF8()`.

2023-10-27 11:22 UTC, GMishx commented on src/lib/php/common-sysconfig.php
Can add type `: void` to `Populate_sysconfig()`.

2023-10-27 11:22 UTC, GMishx commented on src/lib/php/common-sysconfig.php
Type `: int` to `check_IP()`.

2023-10-27 11:22 UTC, GMishx commented on src/lib/php/common-sysconfig.php
Type `: void` to `set_python_path()`.

2023-10-27 11:22 UTC, GMishx commented on src/lib/php/common-tags.php
Can add return type `: array` to `GetAllTags()`.

2023-10-27 11:22 UTC, GMishx commented on src/lib/php/common-ui.php
Can add type `: true|string` to `DownloadString2File()`.

2023-10-27 11:22 UTC, GMishx commented on src/lib/php/common-ui.php
Type `: string` to `GetUploadtreeTableName()`.

2023-10-27 11:22 UTC, GMishx commented on src/lib/php/common-ui.php
Type `: string` to `GetUploadName()`.

2023-10-27 11:22 UTC, GMishx commented on src/lib/php/fossdash-config.php
Can add type `: int` to `check_cron_job_inteval()`.

2023-10-27 11:22 UTC, GMishx commented on src/lib/php/fossdash-config.php
Type `: int` to `check_fossology_instance_name()`.

2023-10-27 11:22 UTC, GMishx commented on src/lib/php/fossdash-config.php
Type `: int` to `check_fossdash_cleaning()`.

2023-10-27 11:22 UTC, GMishx commented on src/lib/php/fossdash-config.php
Type `: int` to `check_username()`.

2023-10-27 11:22 UTC, GMishx commented on src/lib/php/fossdash-config.php
Type `: int` to `check_password()`.

2023-11-08 18:46 UTC, vargenau commented
@GMishx 
Hi,
I have implemented the changes you requested, but now I have some tests failing, and I do not understand what the errors are.

2024-05-17 13:30 UTC, closed without merging