feat(api): (1) Upgrade Upload APIs to Version 2
fossology/fossology pull request #2633
Opened 2023-11-13 19:18 UTC by dvjsharma

## Description

This PR addresses tasks 1, 3, 4, 5, 6, 9, 10, and 11 outlined in issue #2623 

### Changes

**Common for all: Moved `groupName` variable from headers to query parameters by making a change in  RestAuthMiddleware**

**Task 1: /updoads/{id}, GET:**
 - moved `groupName` variable  from headers to query params
 - changed the response keys to camelCase
 - modified the unit test to accommodate changes  

**Task 3: /updoads/{id}, DELETE:**

-  moved `groupName` variable  from headers to query params

**Task 4: /updoads/{id}, PATCH:**

-  moved `groupName` variable  from headers to query params

**Task 5: /updoads/{id}, PUT:**
-  moved `groupName`, `folderId`, `action` variable  from headers to query params
-  modified the unit test to accommodate changes  

**Task 6: /updoads, GET:** 
- moved `groupName`, `page`, `limit` variable  from headers to query params

**Task 5: /updoads, GET:** 
- moved `groupName`, `page`, `limit` variable  from headers to query params

**Task 9: /uploads/{id}/item/{itemId}/info, GET:**
- changed the response keys to camelCase 

**Task 10: /uploads/{id}/licenses, GET:**
-  moved `groupName`, `page`, `limit` variable  from headers to query params 
-  changed the response keys to camelCase 

**Task 11: /uploads/{id}/perm-groups, GET:**
-  updated the API Url to `/uploads/{id}/groups/permission`
-  changed the response keys to camelCase 

## How to test

- Changes pass all the unit tests
- Can be tested manually by making requests to the mentioned endpoints using swagger or postman

/cc @dushimsam @GMishx @shaheemazmalmmd

2023-11-15 21:05 UTC, dushsam2 commented
Hello @dvjsharma ,
Would you please squash your commits into one?

2023-11-15 21:10 UTC, dushimsam commented
Hello @dvjsharma , would you please squash these commits into a one?

2023-11-15 21:58 UTC, dvjsharma commented
Done. Please take a look, @dushimsam

2023-11-17 04:14 UTC, GMishx requested changes
Please make the changes version aware as v1 is to be supported in deprecated mode.

2023-11-17 04:14 UTC, GMishx commented on src/www/ui/api/Controllers/UploadController.php
> +    $page = $query[self::PAGE_PARAM] ?? "";
The API should still support V1 requests in deprecated mode until it is completely removed. You can read the version of request with `ApiVersion::getVersion($request) == ApiVersion::V2`.

See https://github.com/fossology/fossology/pull/2617/files#diff-1bae1ab555e908fff79a5b02ff0f05677a8d1f5653259e98531071acfeb7e16bR42 for reference.

2023-11-17 04:14 UTC, GMishx commented on src/www/ui/api/Controllers/UploadController.php
> +    $action = $queryParams['action'] ?? "";
The API should still support V1 requests in deprecated mode until it is completely removed. You can read the version of request with `ApiVersion::getVersion($request) == ApiVersion::V2`.

See https://github.com/fossology/fossology/pull/2617/files#diff-1bae1ab555e908fff79a5b02ff0f05677a8d1f5653259e98531071acfeb7e16bR42 for reference.

2023-11-17 04:14 UTC, GMishx commented on src/www/ui/api/Controllers/UploadController.php
>        $finalPermGroups[] = $value;
I would instead recommend to create a new model and get the version aware array from it. See https://github.com/fossology/fossology/pull/2617/files#diff-f62f1d2b860c504c87d386cdfa79513c109848593f0afeb60a5dc76e4b98ff42 for reference.

2023-11-17 04:14 UTC, GMishx commented on src/www/ui/api/Models/FileInfo.php
> +      'reuseInfo' => $this->reuse_info
I would instead recommend to make the model version aware. See https://github.com/fossology/fossology/pull/2617/files#diff-f62f1d2b860c504c87d386cdfa79513c109848593f0afeb60a5dc76e4b98ff42 for reference.

2023-11-17 04:14 UTC, GMishx commented on src/www/ui/api/Models/Upload.php
>        "hash"        => $this->hash->getArray()
I would instead recommend to make the model version aware. See https://github.com/fossology/fossology/pull/2617/files#diff-f62f1d2b860c504c87d386cdfa79513c109848593f0afeb60a5dc76e4b98ff42 for reference.

2023-11-17 04:14 UTC, GMishx commented on src/www/ui/api/documentation/openapiv2.yaml
> +  url: https://github.com/fossolo/gy/fossology/wiki/FOSSology-REST-API
Irrelevant change. Please revert.

2023-11-17 04:14 UTC, GMishx commented on src/www/ui_tests/api/Models/UploadTest.php
>        "hash"        => $hash->getArray()
Please make the tests version aware. See https://github.com/fossology/fossology/pull/2617/files#diff-97059fc9a26e02adf4caa85aa5714fe79354dd2c7a33b9d5b303e8be10404834 for reference.

2023-11-17 14:45 UTC, dvjsharma commented
Hello @GMishx , I have made the following changes as requested: 

-  Added support for both API versions, now  V1 requests can also be made until it is completely removed.
-  Created 2 new models namely `GroupPermission.php` and `Permissions.php` as requested and modified existing models to make them version aware and respond accordingly.
-  Modified unit tests to make them version aware.

Please take a look and suggest changes, Thanks!

2023-11-24 07:34 UTC, dvjsharma commented
Hi @GMishx , I've made changes for the tests to work. Please review, Thanks!

2023-12-13 09:45 UTC, dvjsharma commented
Hi @GMishx , Friendly reminder to review the latest changes in the PR. Your input is appreciated. Thanks!

2023-12-15 13:20 UTC, GMishx requested changes
Minor changes. Rest looks good.

2023-12-15 13:20 UTC, GMishx commented on src/www/ui/api/Models/GroupPermission.php
> +        ];
Please use 2 space indentation.

2023-12-15 13:20 UTC, GMishx commented on src/www/ui/api/Models/Permissions.php
> +    ];
Please use 2 space indentation.

2023-12-15 13:59 UTC, dvjsharma commented
Hi @GMishx , I've done the indentation changes, PTAL 
Thanks!

2024-01-26 11:38 UTC, GMishx approved these changes
Changes looks good.

2024-01-29 05:15 UTC, GMishx approved these changes
Tested, working as expected.

2024-01-29 05:16 UTC, merged