feat(api): (2) Upgrade upload APIs to Version 2
fossology/fossology pull request #2634
Opened 2023-11-13 19:18 UTC by Akashsah2003

## Description

This PR aims to do tasks 7, 8, 12, 14, 15, 16, 17 of issue #2623.

### Changes

1. **Moved `groupName` variable from headers to query parameters**

2. **/updoads**, POST
- Moved `folderId` , `uploadDescription`, `public`, `applyGlobal`, `ignoreScm`, `uploadType` variables from the headers to body parameters.
- Changed unit test for the controller.
3. **/uploads/{id}/agents**, GET
- Changed these fields to camelCase: `agent_id`, `agent_rev`, `agent_name`
4. **/uploads/{id}/licenses/edited**, GET
- Changed these fields to camelCase: `spdx_id`
5. **/uploads/{id}/licenses/scanned**, GET
- Changed these fields to camelCase: `shortname`
6. **/uploads/{id}/item/{itemId}/tree/view**, GET
- Moved `page` , `limit` variables from the headers to query parameters.

## How to test

- Changes pass all the unit tests.
- Can be tested manually using postman or swagger.

/cc @dushimsam @GMishx @shaheemazmalmmd

2023-11-15 21:09 UTC, dushimsam commented
Hello @Akashsah2003 , these changes should go a long with updating the API documentation of the version-2 APIs

2023-11-16 07:54 UTC, Akashsah2003 commented
Hello @dushimsam, changes made to documentation. Please take a look.

2023-11-17 04:10 UTC, GMishx requested changes
Please support both version 1 and 2 of the API.

2023-11-17 04:10 UTC, GMishx commented on src/www/ui/api/Controllers/UploadController.php
> +    $uploadType = $reqBody['uploadType'] ?? null;
The API should still support V1 requests in deprecated mode until it is completely removed. You can read the version of request with `ApiVersion::getVersion($request) == ApiVersion::V2`.

See https://github.com/fossology/fossology/pull/2617/files#diff-1bae1ab555e908fff79a5b02ff0f05677a8d1f5653259e98531071acfeb7e16bR42 for reference.

2023-11-17 04:10 UTC, GMishx commented on src/www/ui/api/Controllers/UploadController.php
> +        unset($agent['agent_rev']);
I would instead recommend to create a new model and get the version aware array from it. See https://github.com/fossology/fossology/pull/2617/files#diff-f62f1d2b860c504c87d386cdfa79513c109848593f0afeb60a5dc76e4b98ff42 for reference.

2023-11-17 04:10 UTC, GMishx commented on src/www/ui/api/Middlewares/RestAuthMiddleware.php
> +      $groupName = $query["groupName"] ?? null;
Please keep it version aware.

2023-11-17 04:10 UTC, GMishx commented on src/www/ui/api/Controllers/UploadController.php
>        $uploadType = 'vcs';
As per the OpenAPI doc, `uploadType` is a required field and thus, should throw appropriate exception if empty.

2023-11-17 14:45 UTC, Akashsah2003 commented
I have made the following changes @GMishx

- Added support for both Version1 and Version2 for apis.
- `uploadType` is now throwing bad request exception.
- Created models `Agent.php`, `SuccessfulAgent.php`, `EditedLicense.php` in order to support both API V1 and V2 responses.
- Modified Unit tests accordingly.

2023-11-24 07:34 UTC, Akashsah2003 commented
@GMishx I have made the commit so that tests pass. Kindly review the pr.

2023-12-15 13:31 UTC, GMishx requested changes
Minor changes, rest looks good.

2023-12-15 13:31 UTC, GMishx commented on src/www/ui/api/Controllers/UploadController.php
> +    };
Irrelevant changes, please revert.

2023-12-15 13:31 UTC, GMishx commented on src/www/ui/api/Controllers/UploadController.php
> +    } elseif ($reqBody['uploadType'] != 'file') {
Better use `$uploadType` variable already assigned based on API version.

2023-12-15 13:31 UTC, GMishx commented on src/www/ui/api/Models/Agent.php
> +    ];
Please use 2 space indentation.

2023-12-15 13:31 UTC, GMishx commented on src/www/ui/api/Models/EditedLicense.php
> +    ];
Please use 2 space indentation.

2023-12-15 13:31 UTC, GMishx commented on src/www/ui/api/Models/Agent.php
> +    ];
Both the responses (v1 and v2) looks same to me. Can the check be simply removed?

2023-12-15 13:31 UTC, GMishx commented on src/www/ui/api/Models/SuccessfulAgent.php
> +    ];
Please use 2 space indentation.

2023-12-15 14:20 UTC, Akashsah2003 commented
Hi @GMishx I have made the required changes. Please take a look.

2023-12-25 06:27 UTC, Akashsah2003 commented
Hi @GMishx , Friendly reminder to review the latest changes in the PR. Your input is appreciated. Thanks!

2024-01-29 05:21 UTC, GMishx approved these changes
Changes looks good.

2024-01-29 05:58 UTC, GMishx approved these changes
Tested, working as expected.

2024-01-29 06:02 UTC, merged