Update DecisionImporterDataCreator.php
fossology/fossology pull request #2658
Opened 2023-12-19 12:26 UTC by Kgitman

Description

During import it could happen, in createClearingDecisions() the variable $newCeId is null:
Issue : #2656 

Changes

Added a null pointer check and continue;

/cc @GMishx

2023-12-20 11:04 UTC, GMishx requested changes
Please update the commit message according to our [contributing guidelines](https://github.com/fossology/fossology/blob/b6a5a655019260a3fac9008a568cbc22b2f92fb3/CONTRIBUTING.md#git-commit-conventions).

2023-12-21 02:31 UTC, Kgitman commented
Ok, 
So i have to just edit the commit message according to your contributing guidelines? 
No need to change the code?

2023-12-21 04:46 UTC, GMishx commented
Yes, code changes are good. Please change just the commit message.

2023-12-22 03:11 UTC, Kgitman commented
Done?

2023-12-22 15:19 UTC, GMishx commented
I see no difference @Kgitman

2023-12-22 15:41 UTC, Kgitman commented
Sorry for that i changed the description , I edited the commit message please review. 
@GMishx

2023-12-22 15:45 UTC, GMishx commented
Oh, I see. But I meant the actual commit message, not the PR title or description. Since it is the once which will end up in the commit history.

2023-12-23 03:27 UTC, Kgitman commented
Is this ok? Please review. 
@GMishx

2023-12-23 07:07 UTC, GMishx approved these changes
LGTM

2023-12-23 07:08 UTC, GMishx commented
> Is this ok? Please review. @GMishx

Not exactly, was expecting to have only 1 commit at the end (using `git commit --amend`). But I guess I can squash the commits while merging.

2023-12-23 08:05 UTC, merged