fix(spdx): replaced & with &quot;
fossology/fossology pull request #2689
Opened 2024-02-28 12:21 UTC by Akashsah2003

## Description

Replaced `&` with `&quot;` in the `<rdfs:seeAlso>` tag.

## How to test

1.) Create a test file with SPDX-License-Identifier: BitTorrent-1.0.
2.) Scan the file with ojo.
3.) Export SPDX RDF report.

 Fixes #2688 

CC @GMishx @shaheemazmalmmd

2024-02-28 13:49 UTC, GMishx commented
Shouldn't `&` be replaced by `&amp;`, instead of `&quote;` for `"`?

2024-02-28 14:35 UTC, Akashsah2003 commented
> Shouldn't `&` be replaced by `&amp;`, instead of `&quot;` for `"`?

Yes it should be `&amp;`. I have made the changes. Please take a look.

2024-03-05 10:24 UTC, GMishx commented
I just checked the SPDX RDF specification. They have marked the datatype of the field `rdf:seeAlso` as `xsd:anyURI`. As per the XSD specification, the URI's should be `%` encoded.
Thus, I will recommend to use the [url_encode](https://twig.symfony.com/doc/3.x/filters/url_encode.html) function in twig rather than replacing `&` with `&amp;` as it makes the URI invalid.

See: http://www.datypic.com/sc/xsd/t-xsd_anyURI.html

2024-03-05 13:24 UTC, Akashsah2003 commented
> I just checked the SPDX RDF specification. They have marked the datatype of the field `rdf:seeAlso` as `xsd:anyURI`. As per the XSD specification, the URI's should be `%` encoded. Thus, I will recommend to use the [url_encode](https://twig.symfony.com/doc/3.x/filters/url_encode.html) function in twig rather than replacing `&` with `&amp;` as it makes the URI invalid.
> 
> See: http://www.datypic.com/sc/xsd/t-xsd_anyURI.html

Thanks @GMishx .I encoded the URI for `rdfs:seealso`. Also should we encode other URIs such as `rdf:about`? I observed the following code segment  in `listedlicense.xml.twig` tries to encode the `rdf:about` URI but is not working properly.

`<spdx:ListedLicense rdf:about="http://spdx.org/licenses/{{ licenseObj.spdxId|replace({' ': '-'})|url_encode }}">`

This should instead be replaced by
`<spdx:ListedLicense rdf:about="{{ ( "http://spdx.org/licenses/" ~ licenseList[res].licenseObj.spdxId)|replace({' ': '-'})|url_encode }}">`

2024-03-06 06:03 UTC, GMishx commented
> Thanks @GMishx .I encoded the URI for `rdfs:seealso`. Also should we encode other URIs such as `rdf:about`? I observed the following code segment in `listedlicense.xml.twig` tries to encode the `rdf:about` URI but is not working properly.
> 
> `<spdx:ListedLicense rdf:about="http://spdx.org/licenses/{{ licenseObj.spdxId|replace({' ': '-'})|url_encode }}">`
> 
> This should instead be replaced by `<spdx:ListedLicense rdf:about="{{ ( "http://spdx.org/licenses/" ~ licenseList[res].licenseObj.spdxId)|replace({' ': '-'})|url_encode }}">`

Nice catch @Akashsah2003 , please go ahead with the changes in same PR.

2024-03-06 10:22 UTC, Akashsah2003 commented
> > Thanks @GMishx .I encoded the URI for `rdfs:seealso`. Also should we encode other URIs such as `rdf:about`? I observed the following code segment in `listedlicense.xml.twig` tries to encode the `rdf:about` URI but is not working properly.
> > `<spdx:ListedLicense rdf:about="http://spdx.org/licenses/{{ licenseObj.spdxId|replace({' ': '-'})|url_encode }}">`
> > This should instead be replaced by `<spdx:ListedLicense rdf:about="{{ ( "http://spdx.org/licenses/" ~ licenseList[res].licenseObj.spdxId)|replace({' ': '-'})|url_encode }}">`
> 
> Nice catch @Akashsah2003 , please go ahead with the changes in same PR.

I have made the changes. Please take a look.

2024-03-06 10:35 UTC, GMishx approved these changes
Changes looks good.

2024-03-07 11:03 UTC, GMishx commented
Looks like the recent changes made everything super encoded. The data license's URI became `http%3A%2F%2Fspdx.org%2Flicenses%2FCC0-1.0` instead of `http://spdx.org/licenses/CC0-1.0` and that causes the test to fail.

Looks like, we should restrict the `url_encode` to just `rdfs:seeAlso` of a license if it contains an `&`. Otherwise it can have lot of unintended issues.

2024-03-08 06:32 UTC, GMishx requested changes

2024-03-08 06:32 UTC, GMishx commented on src/spdx2/agent/template/listedlicense.xml.twig
> +<spdx:ListedLicense rdf:about="{{ ( "http://spdx.org/licenses/" ~ licenseObj.spdxId)|replace({' ': '-'}) }}">
What I meant is to revert this change, not to remove the `url_encode`.

2024-03-08 06:32 UTC, GMishx commented on src/spdx2/agent/template/listedlicense.xml.twig
> +  <rdfs:seeAlso>{{ licenseObj.url|url_encode }}</rdfs:seeAlso>
Also, please do this `url_encode` **only** if there is an `&` in the `licenseObj.url` otherwise other tools reading this file might break.

2024-03-08 06:32 UTC, GMishx commented on src/spdx2/agent/template/spdx2-document.xml.twig
> +      <rdfs:seeAlso>{{ licenseData.licenseObj.url|url_encode }}</rdfs:seeAlso>
Same `&` check here please.

2024-03-10 12:47 UTC, GMishx approved these changes
Changes looks good.

2024-03-10 13:27 UTC, GMishx approved these changes
Tested, working as expected.

2024-03-10 13:28 UTC, merged