Worked on the issue #2084 --> Fix Fossology agent tests. tests_common…
fossology/fossology pull request #2696
Opened 2024-03-07 17:02 UTC by mridul45

…_menu.php

## Description

Please describe the changes in your pull request in few words here.

### Changes

List the changes done to fix a bug or introducing a new feature.

## How to test

Describe the steps required to test the changes proposed in the pull request.

Please consider using the closing keyword if the pull request is proposed to
fix an issue already created in the repository
(https://help.github.com/articles/closing-issues-using-keywords/)

2024-03-08 06:39 UTC, GMishx requested changes

2024-03-08 06:39 UTC, GMishx commented on src/lib/php/tests/test_common_menu.php
> -*/
Please do not remove copyrights.

2024-03-08 06:39 UTC, GMishx commented on src/lib/php/tests/test_common_menu.php
> +namespace YourNamespace\Tests;
Please use better namespace name.

2024-03-08 06:39 UTC, GMishx commented on src/lib/php/tests/test_common_menu.php
> -
Please do not remove doc string documenting the file.

2024-03-08 06:39 UTC, GMishx commented on src/lib/php/tests/test_common_menu.php
> + * Test suite for common-menu.php
Please use `\class` to document the class.

2024-03-08 06:39 UTC, GMishx commented on src/lib/php/tests/test_common_menu.php
> +        $this->assertStringContainsString($expected, $result);
Please use 2 space indentation. Read [coding guidelines](https://github.com/fossology/fossology/wiki/Coding-Style)

2024-03-08 06:39 UTC, GMishx commented
@mridul45 , please fix the commit message. Please follow the commit convention mentioned in [contributing guide](https://github.com/fossology/fossology/blob/2ce7d20684a1e5b3dd14d042cd92b3afa034f6c8/CONTRIBUTING.md#git-commit-conventions)

2024-03-08 06:48 UTC, mridul45 commented
ok sir

2024-03-10 12:46 UTC, GMishx commented
Closing in favor of #2698

2024-03-10 12:46 UTC, closed without merging