feat(ubuntu): support ubuntu noble 24.04 for fossology
fossology/fossology pull request #2760
Opened 2024-06-13 07:45 UTC by shaheemazmalmmd

## Description

Add support for ubuntu jammy 22.04 for fossology.

### Changes

added noble support in installdeps file and many other.

## How to test

* Test every functionality of fossology using source install as well as debian install in Ubuntu 24.04

<a href="https://gitpod.io/#https://github.com/fossology/fossology/pull/2300"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

2024-06-13 11:22 UTC, GMishx requested changes

2024-06-13 11:22 UTC, GMishx commented on debian/control
Please update the changes in `cmake/FoPackaging.cmake` as well.

2024-06-13 12:38 UTC, shaheemazmalmmd commented on debian/control
Done

2024-06-27 06:51 UTC, GMishx approved these changes
Changes looks good.

2024-06-27 06:51 UTC, merged