Fix(monk): Filter bulk scan files by agent for current upload
fossology/fossology pull request #2859
Opened 2024-10-21 09:40 UTC by its-sushant

## Description
Fix(monk): Filter bulk scan files by agent for current upload

## Changes
This change resolves an issue where files with valid license findings
from a recent scan could be mistakenly filtered out due to older entries
in the `license_file` table.

##Fixes
https://github.com/fossology/fossology/issues/2799

CC: @shaheemazmalmmd @GMishx

2024-12-21 18:48 UTC, OliverFendt commented
@shaheemazmalmmd it would be really nice if this bug will be fixed soon. It is annoying in the daily work.
Thank you very much

2025-01-06 06:39 UTC, Kaushl2208 requested changes
Can you fix these changes, I will move ahead on testing this.

2025-01-06 06:39 UTC, Kaushl2208 commented on src/monk/agent/database.c
> +                       " JOIN LICENSE_REF_TABLE lr ON lf.rf_fk = lr.rf_pk"
`LICENSE_REF_TABLE` is a macro, should be outside string. It must be behaving as literal Right now.

2025-01-06 06:39 UTC, Kaushl2208 commented on src/monk/agent/database.c
> +                       " AND lr.rf_shortname = ANY(ARRAY['No_license_found', 'Void']))";
`ANY(ARRAY[])` is not highly optimised, use `ANY(VALUES())` ?

2025-01-06 07:09 UTC, its-sushant commented
@Kaushl2208 Thank you for the review. I made the suggested changes. Please let me know if any other change is required.

2025-01-07 08:38 UTC, Kaushl2208 commented
Tested, working as expected :)
Thanks for the contribution @its-sushant

2025-01-07 08:39 UTC, Kaushl2208 approved these changes

2025-01-07 08:46 UTC, merged