Feat: Licenses import from LicenseDB
fossology/fossology pull request #2876
Opened 2024-12-13 19:19 UTC by Kaushl2208

## Description

Fossology needs a functionality to pull license data from LicenseDB.

### Changes

## How to test

2024-12-23 15:21 UTC, GMishx requested changes

2024-12-23 15:21 UTC, GMishx commented on src/lib/php/Plugin/DefaultPlugin.php
> +    if (array_key_exists('LOGDIR', $SysConf['DIRECTORIES'])) {
```suggestion
    if (array_key_exists('DIRECTORIES', $SysConf) && array_key_exists('LOGDIR', $SysConf['DIRECTORIES'])) {
```

2024-12-23 15:21 UTC, GMishx commented on src/lib/php/Plugin/test/DefaultPluginTest.php
> +    ];
Invalid way to fix test cases :-)

2024-12-23 15:21 UTC, GMishx commented on src/lib/php/common-sysconfig.php
> +    "null");
Please add default value `/api/v1`

2024-12-23 15:21 UTC, GMishx commented on src/lib/php/common-sysconfig.php
> +    strval(CONFIG_TYPE_TEXT), "'LicenseDB'", "3", "'$desc'", "null", "null");
Please add default value `/licenses/export`

2024-12-23 15:21 UTC, GMishx commented on src/lib/php/common-sysconfig.php
> +  $desc = _('URL to LicenseDB servers');
```suggestion
  $desc = _('URL to LicenseDB server');
```

2024-12-23 15:21 UTC, GMishx commented on src/lib/php/common-sysconfig.php
> +    strval(CONFIG_TYPE_INT), "'LicenseDB'", "4", "'$desc'", "null", "null");
Unused variable, please remove.

2024-12-23 15:21 UTC, GMishx commented on src/www/ui/page/AdminLicenseFromCSV.php
> +        $this->fileLogger->debug("****************** End Message From LicenseDB ******************");
```suggestion
        $this->fileLogger->debug("****************** Message From LicenseDB import [" . date('Y-m-d H:i:s') . "] ******************");
        $this->fileLogger->debug($vars["message"]);
        $this->fileLogger->debug("****************** End Message From LicenseDB import ******************");
```

2024-12-23 15:21 UTC, GMishx commented on src/www/ui/page/AdminLicenseFromCSV.php
> +  public function handleLicenseDbImport(): string
Please remove return type as it causes trouble with old PHP versions.

2024-12-23 15:21 UTC, GMishx commented on src/www/ui/page/AdminLicenseFromCSV.php
> +  public function checkLicenseDBHealth(): bool
Please remove return type as it causes trouble with old PHP versions.

2024-12-23 15:21 UTC, GMishx commented on src/www/ui/page/AdminLicenseFromCSV.php
> +    $getUsers = $this->configuration['url'] . $this->configuration['uri'] . "/health";
Endpoint is for health, variables is called users, which is confusing.

2024-12-23 15:21 UTC, GMishx commented on src/www/ui/template/admin_license_from_licensedb.html.twig
> +{# SPDX-FileCopyrightText: © 2014-2015 Siemens AG
```suggestion
{# SPDX-FileCopyrightText: © 2024 Siemens AG
```

2025-01-09 12:53 UTC, Kaushl2208 commented on src/lib/php/common-sysconfig.php
> +    strval(CONFIG_TYPE_TEXT), "'LicenseDB'", "3", "'$desc'", "null", "null");
They are the default value.

2025-01-09 14:01 UTC, GMishx approved these changes
Changes looks good

2025-01-10 07:51 UTC, shaheemazmalmmd approved these changes
Tested works as expected.

2025-01-10 07:52 UTC, merged