fix(UI bug): Show Button Not Appearing After Hiding Folder Navigation under Browse tab
fossology/fossology pull request #2882
Opened 2024-12-19 16:00 UTC by abhishekrj02

## Description
This PR resolves a minor UI bug related to issue #2879 . The issue was related to the visibility toggle not properly triggering the display of the "Show" button.

## Changes Made:

ui-browse.html.twig:
- Removed 'hidden' attribute from element of id = 'nav-shower' and added to it style="display none". 

ui-browse.js.twig:
- added $('#nav-shower').css("display", "flex"); 
- removed $('#nav-shower').show('slow'); 

When we show it with $('#nav-shower').show('slow'), the element might not behave properly due to the hidden property persisting. So I have changed its display style.

CC: @shaheemazmalmmd @GMishx

![Screenshot from 2024-12-19 12-28-38](https://github.com/user-attachments/assets/39551318-7ed1-49c3-816a-37a4f7b8ad90)

2025-01-15 08:01 UTC, Kaushl2208 requested changes
![image](https://github.com/user-attachments/assets/3411f040-adb0-466a-ac93-57a310544816)

This right arrow looks very weird tbh.
Also instead hardcoding the sizes, try to make them relative.

The `X` button is from bootstrap, Follow the same style and make this right arrow button.

2025-01-15 08:20 UTC, abhishekrj02 commented on src/www/ui/template/ui-browse.html.twig
> +          <span style="font-size:36px; ">&raquo;</span>
Okay, I will do it.

2025-01-16 17:36 UTC, abhishekrj02 commented on src/www/ui/template/ui-browse.html.twig
> +          <span style="font-size:36px; ">&raquo;</span>
@Kaushl2208 I have bootstraped the icon, and also removed slow hide as it is looking kind of weird.

2025-01-17 09:36 UTC, shaheemazmalmmd commented
@abhishekrj02 : We have observed that this issue has been already contributed some time ago. But somehow we have mot merged that. 

Thanks again for your contributions looking Forword.

2025-01-17 09:36 UTC, closed without merging