fix: improve duplicate file warning UI (#2900)
fossology/fossology pull request #2902
Opened 2024-12-27 20:12 UTC by Vaibhavsahu2810

## Description
This pull request improves the duplicate file warning UI on the upload page. The current popover warning has several issues, such as inconsistent positioning, lack of visibility, and unclear actions for users.

The proposed solution replaces the popover with a centered, responsive modal dialog that:

Clearly displays duplicate files and their details (file name, upload date).
Provides actionable buttons:
"Continue Anyway": Proceeds with the upload.
"Clear Selection": Resets the file selection.
Enhances user experience with better visibility, accessibility, and mobile responsiveness.
## How to Test
Upload a new file: No warning modal should appear.
Upload an existing file: The warning modal should appear with duplicate file details and action buttons.
Test "Continue Anyway" and "Clear Selection" buttons to ensure they work as expected.
Verify responsiveness on different screen sizes (desktop, tablet, mobile).
## Proof of work

https://github.com/user-attachments/assets/5df97d2c-dc78-4680-9f31-a76ae6a94b4f

2024-12-27 20:43 UTC, Vaibhavsahu2810 commented
I have mistakenly added the false commit messages but fixed it in the latest commit message

2025-01-02 15:07 UTC, Kaushl2208 commented
Hey @Vaibhavsahu2810 , Before reviewing the code! I have some suggestions regarding the pop-up:

1. The `View Upload` button should not be there, looks odd. Keep it as the HyperLink (previous warning)
2. The Red Color signifies heavy warning in general, Nature of this specific duplicate upload is a notification so any color close to Grey would do the perfect job.
3. Another question, whats the actual difference between `Continue Anyway` button and the `X Button` on top?

2025-01-02 20:47 UTC, Vaibhavsahu2810 commented
Hello @Kaushl2208 ,
made changes as needed for 1&2,
Actually `X` button and `Continue Anyway`  button serve the exact same purpose ,i added it for good user experience but removed now

2025-01-03 12:29 UTC, Kaushl2208 commented
Hey @Vaibhavsahu2810 , I didnt mean to remove the button itself. I understood the UX part but was just curious if they do the same job.

My suggestion would be to keep: `Continue Anyway` but let it be the secondary button, Make `Clear Selection` the primary button.

2025-01-03 12:30 UTC, Kaushl2208 requested changes

2025-01-03 12:30 UTC, Kaushl2208 commented on src/www/ui/template/upload_file.html.twig
> +                <div class="modal-header" style="background-color: rgb(108, 117, 125); color: white;">
Also dont hard-code the colors. Use bootstrap based colors :)

2025-01-04 21:52 UTC, Vaibhavsahu2810 commented on src/www/ui/template/upload_file.html.twig
> +                <div class="modal-header" style="background-color: rgb(108, 117, 125); color: white;">
Done

2025-01-04 21:54 UTC, Vaibhavsahu2810 commented
<img width="850" alt="image" src="https://github.com/user-attachments/assets/9a1ee15f-ea64-45ee-8078-9cc12daecb51" />
Hello @Kaushl2208 ,now is this looks good?

2025-01-08 05:07 UTC, Kaushl2208 requested changes
@Vaibhavsahu2810 , Squash  multiple commits.  Follow [Contibuting Guidelines](https://github.com/fossology/fossology/blob/master/CONTRIBUTING.md)

2025-01-08 05:07 UTC, Kaushl2208 commented
Changes Looks Good to me. I have tested the functionality it is working fine. Once the commits are squashed can be merged.

2025-01-10 05:34 UTC, dakshmehta007 commented
Is this issue still open?

2025-01-10 12:28 UTC, GMishx commented
> Is this issue still open? 
> 

This is a PR @dakshmehta007 closing the issue.

2025-01-12 08:52 UTC, Vaibhavsahu2810 commented
Hello @Kaushl2208 , squash done!

2025-01-13 05:56 UTC, Kaushl2208 approved these changes
Changes looks good. Ready to merge👍

2025-01-15 07:25 UTC, shaheemazmalmmd commented
@Vaibhavsahu2810 please change the commit message to "<type>(<scope>): <subject>" format. refer [CONTRIBUTING](https://github.com/fossology/fossology/blob/master/CONTRIBUTING.md) for more details.

2025-01-16 12:46 UTC, Vaibhavsahu2810 commented
Done! :)

2025-02-03 15:30 UTC, dvjsharma commented
Hey @Vaibhavsahu2810. The commit message still does not follow the guidelines. Please change it to `<type>(<scope>): <subject>` format.

2025-03-18 18:56 UTC, shaheemazmalmmd commented
@Vaibhavsahu2810 : can you please squash the commits to one ?? i see that there an additional merge commit added.

2025-03-23 09:28 UTC, Vaibhavsahu2810 commented
I encountered a divergent branch issue while pulling the latest changes from my branch (Vaibhavsahu2810/2900/Improved-Warning-UI). To avoid further conflicts, I will close this PR and open a new one with the latest updates.

2025-03-23 09:28 UTC, closed without merging