updated outdated nomos developer notes
fossology/fossology pull request #2903
Opened 2024-12-30 18:32 UTC by laky241

fixes #2795 

This PR updates the nomos developers notes to integrate with the standard FOSSology CMake build system and addresses a few key configuration requirements:

Build System Update: Migrated from a custom Makefile to CMake.

PostgreSQL Dependency: Added PostgreSQL development header requirement for building the agent.

Configuration Documentation: Documented the need for the fossology.conf file and its location.

**WHAT CHANGES I HAVE MADE**

We've migrated nomos from a custom Makefile to the standard CMake build system.

Added a requirement for PostgreSQL development headers (libpq-dev) for the build.

Documented the need for the fossology.conf file, which should be placed in /etc/fossology/ or a custom location defined by the FOSS_CONFIG variable.

2025-01-03 11:56 UTC, Kaushl2208 commented
@laky241 , The earlier Agent Notes looks more like personal notes from the developer and I am not sure if its the documentation that needs to be followed. I am not sure how much of the TODOs or Questions still exists.

@GMishx @shaheemazmalmmd thoughts?

2025-01-04 18:20 UTC, laky241 commented
Hi @Kaushl2208 
I was just trying to address issue #2795, which seemed to be about updating the outdated Agent Notes for nomos. My goal was to clean them up and make them more aligned with the current state of the agent.

If I got something wrong or misunderstood the issue, please let me know. I'd be happy to fix it or make any changes you suggest!

2025-01-10 08:36 UTC, Kaushl2208 requested changes

2025-01-10 08:36 UTC, Kaushl2208 commented on src/nomos/agent/Notes
> -
Hey @laky241 , Apart from the postgres dependency and CMAKE changes revert all the changes as it is. Let the document just reflect the change in build system and postgres dependency. Lets not touch the other things meanwhile.

2025-01-10 08:36 UTC, Kaushl2208 commented on src/nomos/agent/Notes
> +
Revert back all this to previous version

2025-01-11 17:16 UTC, laky241 commented on src/nomos/agent/Notes
> -
done

2025-01-11 17:16 UTC, laky241 commented on src/nomos/agent/Notes
> +
done

2025-01-13 05:41 UTC, Kaushl2208 requested changes
Changes looks good @laky241. Can you please squash the commits?

2025-01-13 18:01 UTC, laky241 commented
Hi @Kaushl2208 i tried to squash the commits but i am not sure i have done correct or not as this is the first time i am doing it, so please guide me if i have done anything wrong.

2025-01-15 04:56 UTC, Kaushl2208 commented
Hi @laky241 , You need to use `git rebase -i HEAD^n` (where n is the number of commits needs to be rebased from HEAD). Then squash the older commits on to the top commit. Do the same with the commit messages window.
You can follow this guide: [Basic Guide For Squashing Commits Interactively](https://gist.github.com/lioncash/fbf57f875575d3e13484)

2025-01-15 17:41 UTC, laky241 commented
@Kaushl2208 thanks sir for your guidance i think i have successfully squashed the commits.

2025-01-20 05:45 UTC, shaheemazmalmmd commented
@laky241 : can you squash the commits to one ??

2025-01-20 17:45 UTC, laky241 commented
@shaheemazmalmmd I've confirmed the commits are squashed into one. if i have done any mistake please guide.

2025-01-21 05:02 UTC, Kaushl2208 commented
> @shaheemazmalmmd I've confirmed the commits are squashed into one. if i have done any mistake please guide.

I still am seeing 9 commits @laky241, Instead of merging can you try and squash all the commits?

![image](https://github.com/user-attachments/assets/9d755afa-6bdf-4047-a21f-00a834d396f4)

2025-01-21 08:06 UTC, closed without merging